"""
Generates the diagrams for RCRAInfo-API-Keys-Explained.docx.

Run:  python docs/api-keys/make_diagrams.py
Output: docs/api-keys/img/*.png

Deliberately plain: PIL primitives only, no chart library, so the diagrams
stay legible when printed in black and white and can be regenerated by anyone.
"""

import os
from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "img")
os.makedirs(OUT, exist_ok=True)

FONTDIR = r"C:\Windows\Fonts"
FONTS = {
    "reg": "segoeui.ttf",
    "bold": "segoeuib.ttf",
    "light": "segoeuisl.ttf",
    "mono": "consola.ttf",
}

# Palette: amber = a human must act, green = automatic, red = broken,
# blue = neutral structure. Chosen to stay distinguishable in greyscale.
INK = (28, 37, 51)
INK_SOFT = (88, 101, 122)
WHITE = (255, 255, 255)
BLUE = (31, 78, 121)
BLUE_L = (233, 240, 248)
GREEN = (26, 106, 66)
GREEN_L = (229, 243, 235)
AMBER = (169, 99, 4)
AMBER_L = (253, 243, 224)
RED = (163, 40, 32)
RED_L = (252, 234, 232)
GRAY = (150, 161, 178)
GRAY_L = (244, 246, 249)


class Canvas:
    """Draws in logical pixels, renders at 2x, downsamples for clean edges."""

    def __init__(self, w, h, bg=WHITE, ss=2):
        self.w, self.h, self.ss = w, h, ss
        self.img = Image.new("RGB", (w * ss, h * ss), bg)
        self.d = ImageDraw.Draw(self.img)
        self._fc = {}

    def font(self, kind, size):
        key = (kind, size)
        if key not in self._fc:
            path = os.path.join(FONTDIR, FONTS[kind])
            self._fc[key] = ImageFont.truetype(path, int(size * self.ss))
        return self._fc[key]

    def _s(self, v):
        if isinstance(v, (int, float)):
            return v * self.ss
        return [x * self.ss for x in v]

    def rrect(self, box, r=14, fill=None, outline=None, width=2):
        self.d.rounded_rectangle(self._s(box), radius=self._s(r), fill=fill,
                                 outline=outline, width=int(self._s(width)))

    def rect(self, box, fill=None, outline=None, width=2):
        self.d.rectangle(self._s(box), fill=fill, outline=outline,
                         width=int(self._s(width)))

    def ellipse(self, box, fill=None, outline=None, width=2):
        self.d.ellipse(self._s(box), fill=fill, outline=outline,
                       width=int(self._s(width)))

    def line(self, pts, fill=INK, width=2):
        self.d.line([tuple(self._s(p)) for p in pts], fill=fill,
                    width=int(self._s(width)), joint="curve")

    def poly(self, pts, fill=INK):
        self.d.polygon([tuple(self._s(p)) for p in pts], fill=fill)

    def text(self, xy, s, kind="reg", size=16, color=INK, anchor="la"):
        self.d.text(tuple(self._s(xy)), s, font=self.font(kind, size),
                    fill=color, anchor=anchor)

    def tw(self, s, kind, size):
        return self.d.textlength(s, font=self.font(kind, size)) / self.ss

    def wrap(self, s, kind, size, max_w):
        words, lines, cur = s.split(), [], ""
        for w in words:
            t = (cur + " " + w).strip()
            if self.tw(t, kind, size) <= max_w or not cur:
                cur = t
            else:
                lines.append(cur)
                cur = w
        if cur:
            lines.append(cur)
        return lines

    def para(self, xy, s, kind="reg", size=16, color=INK, max_w=300, lh=1.35,
             anchor="la"):
        x, y = xy
        for ln in self.wrap(s, kind, size, max_w):
            self.text((x, y), ln, kind, size, color, anchor)
            y += size * lh
        return y

    def arrow(self, a, b, color=INK, width=3, head=11):
        import math
        ax, ay = a
        bx, by = b
        ang = math.atan2(by - ay, bx - ax)
        # stop the shaft short so it does not poke through the head
        sx, sy = bx - head * 0.85 * math.cos(ang), by - head * 0.85 * math.sin(ang)
        self.line([(ax, ay), (sx, sy)], color, width)
        self.poly([
            (bx, by),
            (bx - head * math.cos(ang - 0.42), by - head * math.sin(ang - 0.42)),
            (bx - head * math.cos(ang + 0.42), by - head * math.sin(ang + 0.42)),
        ], color)

    def save(self, name):
        out = self.img.resize((self.w, self.h), Image.LANCZOS)
        p = os.path.join(OUT, name)
        out.save(p, "PNG")
        print("wrote", p)


# ----------------------------------------------------------------- icons

def icon_key(c, cx, cy, s=1.0, color=AMBER):
    r = 13 * s
    c.ellipse((cx - r, cy - r, cx + r, cy + r), outline=color, width=5 * s)
    c.line([(cx + r, cy), (cx + r + 34 * s, cy)], color, 5 * s)
    c.line([(cx + r + 14 * s, cy), (cx + r + 14 * s, cy + 12 * s)], color, 5 * s)
    c.line([(cx + r + 27 * s, cy), (cx + r + 27 * s, cy + 12 * s)], color, 5 * s)


def icon_person(c, cx, cy, s=1.0, color=AMBER):
    hr = 11 * s
    c.ellipse((cx - hr, cy - 22 * s, cx + hr, cy), fill=color)
    c.d.pieslice(c._s((cx - 20 * s, cy + 2 * s, cx + 20 * s, cy + 42 * s)),
                 180, 360, fill=color)


def icon_server(c, cx, cy, s=1.0, color=BLUE):
    w, h = 46 * s, 15 * s
    for i in (-1, 0, 1):
        y = cy + i * (h + 5 * s)
        c.rrect((cx - w / 2, y - h / 2, cx + w / 2, y + h / 2), 3 * s,
                fill=WHITE, outline=color, width=3 * s)
        c.ellipse((cx - w / 2 + 6 * s, y - 2.5 * s,
                   cx - w / 2 + 11 * s, y + 2.5 * s), fill=color)


def icon_clock(c, cx, cy, s=1.0, color=GREEN):
    r = 22 * s
    c.ellipse((cx - r, cy - r, cx + r, cy + r), outline=color, width=4 * s)
    c.line([(cx, cy), (cx, cy - 13 * s)], color, 4 * s)
    c.line([(cx, cy), (cx + 10 * s, cy + 5 * s)], color, 4 * s)


def icon_lock(c, cx, cy, s=1.0, color=BLUE):
    c.rrect((cx - 17 * s, cy - 2 * s, cx + 17 * s, cy + 24 * s), 5 * s,
            fill=color)
    c.d.arc(c._s((cx - 11 * s, cy - 20 * s, cx + 11 * s, cy + 4 * s)),
            180, 360, fill=color, width=int(c._s(5 * s)))


def icon_cloud(c, cx, cy, s=1.0, color=BLUE, label=None):
    c.ellipse((cx - 44 * s, cy - 12 * s, cx - 4 * s, cy + 22 * s), fill=color)
    c.ellipse((cx - 20 * s, cy - 26 * s, cx + 24 * s, cy + 20 * s), fill=color)
    c.ellipse((cx + 6 * s, cy - 8 * s, cx + 46 * s, cy + 22 * s), fill=color)
    c.rrect((cx - 42 * s, cy + 6 * s, cx + 44 * s, cy + 22 * s), 8 * s, fill=color)
    if label:
        c.text((cx, cy + 2 * s), label, "bold", 15 * s, WHITE, "mm")


def icon_x(c, cx, cy, r=20, color=RED):
    c.ellipse((cx - r, cy - r, cx + r, cy + r), fill=color)
    k = r * 0.42
    c.line([(cx - k, cy - k), (cx + k, cy + k)], WHITE, r * 0.22)
    c.line([(cx - k, cy + k), (cx + k, cy - k)], WHITE, r * 0.22)


def icon_check(c, cx, cy, r=20, color=GREEN):
    c.ellipse((cx - r, cy - r, cx + r, cy + r), fill=color)
    c.line([(cx - r * 0.45, cy), (cx - r * 0.1, cy + r * 0.38),
            (cx + r * 0.48, cy - r * 0.38)], WHITE, r * 0.22)


def badge(c, cx, cy, n, color, r=21):
    c.ellipse((cx - r, cy - r, cx + r, cy + r), fill=color)
    c.text((cx, cy + 1), str(n), "bold", r * 1.05, WHITE, "mm")


def title(c, s, sub=None, y=34):
    c.text((c.w / 2, y), s, "bold", 30, INK, "ma")
    if sub:
        c.text((c.w / 2, y + 42), sub, "light", 20, INK_SOFT, "ma")


# ------------------------------------------------------- 1. two things

def d1_two_things():
    c = Canvas(1700, 810, GRAY_L)
    title(c, "There are TWO different things. Do not mix them up.",
          "One is made by a person and lasts a long time. The other is made by the app and lasts 20 minutes.")

    cards = [
        dict(x=70, accent=AMBER, wash=AMBER_L, n=1,
             head="THE API KEY", sub="(plus its partner, the API ID)",
             analogy="Like the key to your house.",
             icon="key",
             bullets=[
                 "A PERSON makes it, by hand, on EPA's website.",
                 "It lasts a long time. It does not change by itself.",
                 "EPA shows it on screen ONE time only. Copy it right then.",
                 "It gets locked away on the server.",
                 "Only a PERSON can ever make a new one.",
             ]),
        dict(x=880, accent=GREEN, wash=GREEN_L, n=2,
             head="THE TOKEN", sub="(EPA also calls this a \u201cJWT\u201d)",
             analogy="Like a 20-minute wristband at a water park.",
             icon="clock",
             bullets=[
                 "The APP makes it, automatically.",
                 "It stops working after 20 MINUTES.",
                 "The app just asks for a fresh one. Over and over.",
                 "Nobody ever sees it. It is never written down.",
                 "No person is ever involved. Ever.",
             ]),
    ]

    for cd in cards:
        x, w = cd["x"], 750
        c.rrect((x, 150, x + w, 612), 20, fill=WHITE, outline=cd["accent"], width=3)
        c.rrect((x, 150, x + w, 226), 20, fill=cd["wash"], outline=cd["accent"], width=3)
        c.rect((x + 3, 210, x + w - 3, 226), fill=cd["wash"])
        badge(c, x + 46, 188, cd["n"], cd["accent"], 22)
        c.text((x + 84, 168), cd["head"], "bold", 27, cd["accent"])
        c.text((x + 84, 200), cd["sub"], "reg", 16, INK_SOFT)

        if cd["icon"] == "key":
            icon_key(c, x + 60, 288, 1.5, cd["accent"])
        else:
            icon_clock(c, x + 66, 288, 1.35, cd["accent"])
        c.para((x + 150, 268), cd["analogy"], "bold", 21, INK, max_w=560)

        y = 370
        for b in cd["bullets"]:
            c.ellipse((x + 44, y + 9, x + 56, y + 21), fill=cd["accent"])
            y = c.para((x + 74, y), b, "reg", 19, INK, max_w=630, lh=1.3) + 16

    # the trade, along the bottom
    c.rrect((70, 648, 1630, 762), 16, fill=BLUE_L, outline=BLUE, width=3)
    icon_key(c, 128, 705, 1.1, AMBER)
    c.arrow((208, 705), (300, 705), BLUE, 4, 13)
    icon_cloud(c, 360, 700, 1.0, BLUE, "EPA")
    c.arrow((424, 705), (516, 705), BLUE, 4, 13)
    icon_clock(c, 556, 705, 1.0, GREEN)
    c.para((620, 672),
           "The app shows EPA the KEY, and EPA hands back a TOKEN. "
           "That trade happens over and over, all by itself, forever.",
           "bold", 21, INK, max_w=970)
    c.save("01-two-things.png")


# ------------------------------------------------- 2. how a key is born

def d2_key_is_born():
    c = Canvas(1700, 1112, GRAY_L)
    title(c, "How an API Key is born",
          "Every single step needs a human being. No software can do any of this.")

    steps = [
        ("A person asks EPA for a RCRAInfo account.",
         "Done once for the practice system, and again for the real one."),
        ("MDE's RCRAInfo Administrator approves that account.",
         "This is a person at MDE, not at EPA. Waiting time is unknown."),
        ("The Administrator also grants \u201cTranslation / API Manager\u201d.",
         "Without this extra permission, the Generate button does not exist."),
        ("The person logs in and clicks Generate.",
         "Tools \u2192 Translation/API Maintenance \u2192 Manage API"),
        ("The screen shows the API ID and API Key \u2014 ONCE.",
         "Copy both immediately. EPA will never show the Key again."),
    ]

    y = 168
    for i, (head, sub) in enumerate(steps, 1):
        c.rrect((90, y, 1610, y + 118), 16, fill=WHITE, outline=AMBER, width=3)
        badge(c, 156, y + 59, i, AMBER, 30)
        icon_person(c, 232, y + 44, 0.82, AMBER)
        c.text((300, y + 26), head, "bold", 22, INK)
        c.text((300, y + 62), sub, "reg", 18, INK_SOFT)
        if i < len(steps):
            c.arrow((850, y + 124), (850, y + 152), AMBER, 4, 12)
        y += 158

    c.rrect((90, y + 6, 1610, y + 124), 16, fill=BLUE_L, outline=BLUE, width=3)
    icon_server(c, 168, y + 65, 1.1, BLUE)
    c.text((248, y + 30), "Someone pastes the Key into the server's settings file.",
           "bold", 22, INK)
    c.text((248, y + 66),
           "The app locks it up the first time it runs. After that the file shows scrambled text, not the Key.",
           "reg", 18, INK_SOFT)
    c.save("02-key-is-born.png")


# ------------------------------------------- 3. what happens every night

def d3_every_night():
    c = Canvas(1700, 1020, GRAY_L)
    title(c, "What happens every night, all by itself",
          "This is the answer to \u201chow does the app get a new key?\u201d \u2014 it doesn't. It gets a new TOKEN.")

    # actor header cards, each with a lifeline running down the page
    c.rrect((80, 168, 470, 306), 18, fill=WHITE, outline=BLUE, width=3)
    icon_server(c, 160, 237, 1.2, BLUE)
    c.text((216, 208), "OUR SERVER", "bold", 21, BLUE)
    c.text((216, 240), "the console app", "reg", 17, INK_SOFT)
    c.text((216, 266), "runs unattended", "reg", 17, INK_SOFT)
    c.line([(275, 306), (275, 894)], GRAY, 3)

    c.rrect((1230, 168, 1620, 306), 18, fill=WHITE, outline=BLUE, width=3)
    icon_cloud(c, 1300, 232, 1.15, BLUE, "EPA")
    c.text((1382, 208), "EPA RCRAInfo", "bold", 21, BLUE)
    c.text((1382, 240), "over the internet", "reg", 17, INK_SOFT)
    c.text((1382, 266), "hands out tokens", "reg", 17, INK_SOFT)
    c.line([(1425, 306), (1425, 894)], GRAY, 3)

    rows = [
        (1, "2:00 AM \u2014 Windows starts the app.", "left", GREEN),
        (2, "App unlocks its own copy of the API ID + Key.", "left", GREEN),
        (3, "\u201cHere is my ID and Key. May I have a token?\u201d", "right", GREEN),
        (4, "\u201cYes. Here is a token. It dies in 20 minutes.\u201d", "left", GREEN),
        (5, "App downloads handler records, showing the token each time.", "right", GREEN),
        (6, "About 18 minutes later: token nearly dead \u2192 go back to step 3.", "loop", AMBER),
        (7, "Work finished. App throws the token away and shuts down.", "left", GREEN),
    ]

    y = 370
    for n, txt, kind, col in rows:
        c.rrect((510, y, 1190, y + 62), 12, fill=WHITE, outline=GRAY, width=2)
        badge(c, 546, y + 31, n, col if kind != "loop" else AMBER, 18)
        c.para((580, y + 12), txt, "reg", 18, INK, max_w=590, lh=1.2)
        if kind == "right":
            c.arrow((1196, y + 31), (1419, y + 31), GREEN, 4, 12)
        elif kind == "left":
            c.arrow((504, y + 31), (281, y + 31), GREEN, 4, 12)
        y += 76

    # loop arrow from step 6 back up to step 3, in the gutter left of the boxes
    ly6 = 370 + 5 * 76 + 31
    ly3 = 370 + 2 * 76 + 31
    lx = 462
    c.line([(504, ly6), (lx, ly6)], AMBER, 4)
    c.line([(lx, ly6), (lx, ly3)], AMBER, 4)
    c.arrow((lx, ly3), (504, ly3), AMBER, 4, 12)
    my = 575                                       # a gap no message arrow crosses
    c.rrect((lx - 40, my - 17, lx + 40, my + 17), 10, fill=GRAY_L, outline=AMBER, width=2)
    c.text((lx, my - 9), "repeat", "bold", 16, AMBER, "ma")

    c.rrect((80, 924, 1620, 1000), 14, fill=GREEN_L, outline=GREEN, width=3)
    icon_check(c, 130, 962, 20)
    c.para((172, 940),
           "Steps 3 and 4 may happen hundreds of times in one long run. Nobody is woken up. "
           "The API Key itself is never replaced here.",
           "bold", 20, INK, max_w=1400)
    c.save("03-every-night.png")


# --------------------------------------- 4. when must a human step in

def d4_human_steps_in():
    c = Canvas(1700, 1000, GRAY_L)
    title(c, "When does a person have to get involved?",
          "Only four times. Everything else the app handles on its own.")

    items = [
        ("A brand new server, or a rebuilt one",
         "The locked-up Key only works on the server that locked it. "
         "A person must paste the Key in again on the new machine.",
         "server"),
        ("Moving from practice to the real system",
         "The real EPA system needs a completely different Key. "
         "The practice one will not work there.",
         "cloud"),
        ("The Key suddenly stops working",
         "EPA answers \u201cinvalid credentials.\u201d Usually the person's account or "
         "permission changed. A person must generate a new Key.",
         "x"),
        ("MDE decides to replace the Key on purpose",
         "For example if it may have leaked, or on a routine security schedule. "
         "This is a planned human task.",
         "lock"),
    ]

    x0, y0, w, h = 80, 165, 770, 250
    for i, (head, body, ic) in enumerate(items):
        x = x0 + (i % 2) * (w + 20)
        y = y0 + (i // 2) * (h + 22)
        c.rrect((x, y, x + w, y + h), 18, fill=WHITE, outline=AMBER, width=3)
        c.rrect((x, y, x + w, y + 8), 4, fill=AMBER)
        cx, cy = x + 78, y + 76
        if ic == "server":
            icon_server(c, cx, cy, 1.15, AMBER)
        elif ic == "cloud":
            icon_cloud(c, cx, cy - 4, 1.0, AMBER, "EPA")
        elif ic == "x":
            icon_x(c, cx, cy, 26)
        else:
            icon_lock(c, cx, cy - 6, 1.2, AMBER)
        icon_person(c, cx, y + 176, 0.72, AMBER)
        c.text((cx, y + 226), "human", "bold", 15, AMBER, "ma")
        c.para((x + 156, y + 38), head, "bold", 23, INK, max_w=580, lh=1.22)
        c.para((x + 156, y + 108), body, "reg", 19, INK_SOFT, max_w=580, lh=1.32)

    c.rrect((80, 706, 1620, 838), 18, fill=GREEN_L, outline=GREEN, width=3)
    icon_check(c, 142, 772, 26)
    c.text((196, 726), "And when does a person NOT need to get involved?", "bold", 24, INK)
    c.para((196, 766),
           "When the 20-minute token expires \u2014 which is every 20 minutes, all night long. "
           "The app quietly gets another one. That is not a problem and nobody is told about it.",
           "reg", 19, INK_SOFT, max_w=1370, lh=1.32)

    c.rrect((80, 858, 1620, 972), 18, fill=RED_L, outline=RED, width=3)
    icon_x(c, 142, 915, 26)
    c.para((196, 878),
           "The app can NEVER make itself a new API Key. There is no EPA web address that hands out keys. "
           "A person with a RCRAInfo login must do it, on the website, by hand.",
           "bold", 21, INK, max_w=1370, lh=1.32)
    c.save("04-human-steps-in.png")


# ------------------------------------------------- 5. two environments

def d5_two_worlds():
    c = Canvas(1700, 760, GRAY_L)
    title(c, "Practice EPA and Real EPA are two separate worlds",
          "Two accounts. Two approvals. Two keys. Nothing crosses over.")

    worlds = [
        dict(x=80, name="PRACTICE (\u201cpre-production\u201d)", color=BLUE, wash=BLUE_L,
             url="rcranodepreprod.epa.gov",
             lines=["Its own RCRAInfo account",
                    "Its own Administrator approval",
                    "Its own API ID + API Key",
                    "Safe to experiment in"]),
        dict(x=900, name="REAL (\u201cproduction\u201d)", color=GREEN, wash=GREEN_L,
             url="rcranode.epa.gov",
             lines=["A different RCRAInfo account",
                    "A separate approval, requested again",
                    "A different API ID + API Key",
                    "Real regulated-business data"]),
    ]
    for wd in worlds:
        x, w = wd["x"], 720
        c.rrect((x, 168, x + w, 630), 20, fill=WHITE, outline=wd["color"], width=3)
        c.rrect((x, 168, x + w, 246), 20, fill=wd["wash"], outline=wd["color"], width=3)
        c.rect((x + 3, 230, x + w - 3, 246), fill=wd["wash"])
        icon_cloud(c, x + 66, 202, 0.95, wd["color"], "EPA")
        c.text((x + 130, 184), wd["name"], "bold", 25, wd["color"])
        c.text((x + 130, 216), wd["url"], "mono", 17, INK_SOFT)
        y = 288
        for ln in wd["lines"]:
            icon_key(c, x + 52, y + 12, 0.7, wd["color"])
            c.para((x + 116, y), ln, "reg", 20, INK, max_w=560)
            y += 58
        icon_lock(c, x + 360, 552, 1.4, wd["color"])
        c.text((x + 360, 596), "separate key", "bold", 17, wd["color"], "ma")

    # the barrier
    c.line([(848, 200), (848, 600)], GRAY, 5)
    icon_x(c, 848, 400, 34)
    c.text((848, 452), "will NOT", "bold", 18, RED, "ma")
    c.text((848, 476), "work here", "bold", 18, RED, "ma")

    c.rrect((80, 656, 1620, 736), 14, fill=AMBER_L, outline=AMBER, width=3)
    c.para((122, 676),
           "Ask for BOTH at the same time. Each one has its own waiting period, "
           "so asking one after the other means waiting twice.",
           "bold", 20, INK, max_w=1450)
    c.save("05-two-worlds.png")


# ---------------------------------------------- 6. key locked to server

def d6_locked_to_server():
    c = Canvas(1700, 700, GRAY_L)
    title(c, "The locked-up Key only works on ONE server",
          "This surprises people, so it is worth saying out loud.")

    # server A
    c.rrect((90, 176, 700, 560), 18, fill=WHITE, outline=GREEN, width=3)
    icon_server(c, 200, 250, 1.25, GREEN)
    c.text((280, 224), "Server A", "bold", 24, INK)
    c.text((280, 256), "where the Key was locked", "reg", 17, INK_SOFT)
    c.rrect((140, 316, 650, 424), 12, fill=GRAY_L, outline=GRAY, width=2)
    c.text((166, 334), "settings file", "bold", 15, INK_SOFT)
    c.text((166, 360), '"Encrypted": true', "mono", 17, INK)
    c.text((166, 388), '"ApiKey": "AQAAANCM...8f2b1c"', "mono", 17, GREEN)
    icon_lock(c, 200, 480, 1.1, GREEN)
    c.text((252, 462), "Works here.", "bold", 21, GREEN)
    c.text((252, 492), "This is the machine that locked it.", "reg", 17, INK_SOFT)

    # copy arrow
    c.arrow((716, 368), (846, 368), GRAY, 5, 15)
    c.text((781, 322), "copy the file", "bold", 18, INK_SOFT, "ma")
    icon_x(c, 781, 400, 26)

    # server B
    c.rrect((880, 176, 1610, 560), 18, fill=WHITE, outline=RED, width=3)
    icon_server(c, 990, 250, 1.25, RED)
    c.text((1070, 224), "Server B", "bold", 24, INK)
    c.text((1070, 256), "any other machine", "reg", 17, INK_SOFT)
    c.rrect((930, 316, 1560, 424), 12, fill=RED_L, outline=RED, width=2)
    c.text((956, 334), "same file, copied over", "bold", 15, RED)
    c.text((956, 360), '"Encrypted": true', "mono", 17, INK)
    c.text((956, 388), "cannot be unlocked \u2014 app stops and says so", "reg", 17, RED)
    icon_x(c, 990, 480, 22)
    c.text((1042, 462), "Does not work.", "bold", 21, RED)
    c.text((1042, 492), "A person must paste the Key in again here.", "reg", 17, INK_SOFT)

    c.rrect((90, 590, 1610, 676), 14, fill=AMBER_L, outline=AMBER, width=3)
    c.para((136, 606),
           "So: each server gets set up by hand, once. And if a server is ever rebuilt or replaced, "
           "someone must set it up again \u2014 which needs the Key, which EPA only showed once.",
           "bold", 20, INK, max_w=1440)
    c.save("06-locked-to-server.png")


# --------------------------------------------- 7. the person-shaped risk

def d7_whose_key():
    c = Canvas(1700, 880, GRAY_L)
    title(c, "The one decision management needs to make",
          "Whose name is the Key attached to?")

    # Option A - today
    c.rrect((80, 176, 790, 700), 20, fill=WHITE, outline=RED, width=3)
    c.rrect((80, 176, 790, 250), 20, fill=RED_L, outline=RED, width=3)
    c.rect((83, 234, 787, 250), fill=RED_L)
    c.text((116, 196), "How it works TODAY", "bold", 24, RED)
    icon_person(c, 180, 320, 1.05, RED)
    c.text((180, 380), "one named person", "bold", 17, INK_SOFT, "ma")
    c.arrow((252, 330), (322, 330), GRAY, 4, 13)
    icon_key(c, 380, 330, 1.1, RED)
    c.arrow((466, 330), (536, 330), GRAY, 4, 13)
    icon_server(c, 610, 330, 1.15, RED)
    c.text((610, 386), "nightly download", "bold", 17, INK_SOFT, "ma")
    c.line([(130, 430), (740, 430)], GRAY, 2)
    c.para((130, 452),
           "If that person leaves MDE, changes role, or has their RCRAInfo permission "
           "removed, the Key can stop working \u2014 and the nightly download stops with it.",
           "reg", 19, INK, max_w=610, lh=1.32)
    icon_x(c, 152, 620, 24)
    c.para((196, 596), "A staffing change becomes an outage.", "bold", 20, RED, max_w=560)

    # Option B - recommended
    c.rrect((910, 176, 1620, 700), 20, fill=WHITE, outline=GREEN, width=3)
    c.rrect((910, 176, 1620, 250), 20, fill=GREEN_L, outline=GREEN, width=3)
    c.rect((913, 234, 1617, 250), fill=GREEN_L)
    c.text((946, 196), "What we recommend asking for", "bold", 24, GREEN)
    icon_person(c, 1010, 320, 1.05, GREEN)
    c.text((1010, 380), "a shared MDE account", "bold", 17, INK_SOFT, "ma")
    c.arrow((1082, 330), (1152, 330), GRAY, 4, 13)
    icon_key(c, 1210, 330, 1.1, GREEN)
    c.arrow((1296, 330), (1366, 330), GRAY, 4, 13)
    icon_server(c, 1440, 330, 1.15, GREEN)
    c.text((1440, 386), "nightly download", "bold", 17, INK_SOFT, "ma")
    c.line([(960, 430), (1570, 430)], GRAY, 2)
    c.para((960, 452),
           "The account belongs to MDE, not to an individual. People can come and go and "
           "the download keeps running. Two or three named staff know how to regenerate it.",
           "reg", 19, INK, max_w=610, lh=1.32)
    icon_check(c, 982, 620, 24)
    c.para((1026, 596), "Staffing changes do not break anything.", "bold", 20, GREEN, max_w=560)

    c.rrect((80, 726, 1620, 852), 16, fill=BLUE_L, outline=BLUE, width=3)
    c.text((124, 744), "We do not yet know whether EPA allows a shared account.", "bold", 22, INK)
    c.para((124, 782),
           "That is question 1 on the list at the end of this document. It needs to be asked before "
           "the real-system Key is created, because changing it afterwards means starting the "
           "approval wait over again.",
           "reg", 19, INK_SOFT, max_w=1450, lh=1.3)
    c.save("07-whose-key.png")


if __name__ == "__main__":
    d1_two_things()
    d2_key_is_born()
    d3_every_night()
    d4_human_steps_in()
    d5_two_worlds()
    d6_locked_to_server()
    d7_whose_key()
