using System.Text.Json.Serialization;

namespace RCRAInfo.Loader.Api;

/// <summary>
/// EPA's error envelope, as the pinned spec defines it (<c>spec/rcrainfo/swagger.json</c>, definition
/// <c>ApiError</c>: <c>code</c>, <c>message</c>, <c>errorId</c>, <c>errorDate</c>, all required).
/// </summary>
/// <remarks>
/// <para>
/// <b><see cref="Message"/> is parsed and must not be reported.</b> It is here because the spec says it
/// is always present and because leaving it out would make a future reader think EPA does not send one.
/// It is deliberately never included in any diagnostic this application produces: a message is free text
/// generated by a server and by whatever gateway sits in front of it, and gateways routinely echo the
/// request path they could not route. The auth request's path contains the API ID and Key. So the rule is
/// structural rather than a matter of care — report <see cref="Code"/> and <see cref="ErrorId"/>, which
/// are the two things EPA support asks for, and never the prose.
/// </para>
/// <para>
/// The property names are camelCase in the payload; <c>JsonSerializerDefaults.Web</c> handles that, and
/// the explicit attributes make it survive a change of serializer settings somewhere else.
/// </para>
/// </remarks>
public sealed class ApiError
{
    /// <summary>Bad API ID or Key. Means the credential must be re-seeded.</summary>
    public const string InvalidCredentialsCode = "E_SecurityApiInvalidCredentials";

    /// <summary>
    /// Authenticated, but not permitted the data requested. Means a permissions or scope problem
    /// (Analysis G2) — a different remedy entirely from <see cref="InvalidCredentialsCode"/>.
    /// </summary>
    public const string AccessDeniedCode = "E_AccessDenied";

    /// <summary>EPA's symbolic error code, e.g. <c>E_SecurityApiInvalidCredentials</c>.</summary>
    [JsonPropertyName("code")]
    public string? Code { get; set; }

    /// <summary>EPA's prose. Parsed, never reported — see the remarks on this type.</summary>
    [JsonPropertyName("message")]
    public string? Message { get; set; }

    /// <summary>The identifier EPA support uses to find the failure in their own logs.</summary>
    [JsonPropertyName("errorId")]
    public string? ErrorId { get; set; }

    /// <summary>When EPA recorded the failure.</summary>
    [JsonPropertyName("errorDate")]
    public DateTimeOffset? ErrorDate { get; set; }

    /// <summary>The parts safe to put in front of an operator: the code and the error id.</summary>
    /// <returns>A short description, or an empty string when neither field arrived.</returns>
    public string Describe()
    {
        string code = string.IsNullOrWhiteSpace(Code) ? string.Empty : $"code {Code}";
        string id = string.IsNullOrWhiteSpace(ErrorId) ? string.Empty : $"EPA error id {ErrorId}";

        return (code, id) switch
        {
            ("", "") => string.Empty,
            ("", _) => id,
            (_, "") => code,
            _ => $"{code}, {id}",
        };
    }
}
