/**********************************************************************************************************************
Script:       110_dbo.HandlerSourceRawJson.sql
Author:       generated by build/generate_schema.py
========================================================================================================================
Description:

The raw EPA payload behind each dbo.HandlerSource row, one to one. Separate from the relational table so that the wide
row stays narrow, and so that a scope decision reversed later can be satisfied by re-projection with no EPA re-fetch.

GENERATED FILE -- do not edit by hand. Regenerate with:

    python build/generate_schema.py

Not derived from the spec's field list: this table holds the payload itself.

build/guardrails.py runs `generate_schema.py --check`, which fails if this file and the spec
have drifted apart, so editing it here is not merely discouraged -- it breaks the build.

========================================================================================================================
Notes:

RE-RUNNABLE. Every CREATE is guarded, descriptions go through util.uspSetObjectDescription
(which adds or updates), and nothing is dropped or truncated. A second run changes nothing.

Later changes are ADDITIVE: append a guarded ALTER TABLE ... ADD block rather than editing
the CREATE TABLE above, or the script stops converging on a database that already has the
table. In this file that means changing the generator, not the output.
**********************************************************************************************************************/

SET XACT_ABORT ON;
-- Not decoration: sqlcmd defaults QUOTED_IDENTIFIER OFF where every other client defaults it ON, the
-- setting is BAKED IN at CREATE time, and a module or session carrying it OFF cannot run DML against a
-- table with a filtered index (error 1934). Every unique constraint here is one. Set it so that a hand
-- run cannot get it wrong.
SET QUOTED_IDENTIFIER ON;
GO

----------------------------------------------------------------------------------------------------
-- 1. The table. Guarded, so a second run is a no-op.
----------------------------------------------------------------------------------------------------
IF OBJECT_ID (N'dbo.HandlerSourceRawJson', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.HandlerSourceRawJson
    (
        HandlerSourceId       INT             NOT NULL,
        RawJson               NVARCHAR (MAX)      NULL,
        PayloadSha256         NVARCHAR (64)       NULL,
        RetrievedDateUtc      DATETIME2           NULL,
        IsDeleted             BIT             NOT NULL CONSTRAINT DF_dbo_HandlerSourceRawJson_IsDeleted DEFAULT (0),
        auditDeletedBy        NVARCHAR (128)  NOT NULL CONSTRAINT DF_dbo_HandlerSourceRawJson_auditDeletedBy DEFAULT (ORIGINAL_LOGIN ()),
        auditDeletedDateUtc   DATETIME2       NOT NULL CONSTRAINT DF_dbo_HandlerSourceRawJson_auditDeletedDateUtc DEFAULT (SYSUTCDATETIME ()),
        auditCreatedBy        NVARCHAR (128)  NOT NULL CONSTRAINT DF_dbo_HandlerSourceRawJson_auditCreatedBy DEFAULT (ORIGINAL_LOGIN ()),
        auditCreatedDateUtc   DATETIME2       NOT NULL CONSTRAINT DF_dbo_HandlerSourceRawJson_auditCreatedDateUtc DEFAULT (SYSUTCDATETIME ()),
        auditModifiedBy       NVARCHAR (128)  NOT NULL CONSTRAINT DF_dbo_HandlerSourceRawJson_auditModifiedBy DEFAULT (ORIGINAL_LOGIN ()),
        auditModifiedDateUtc  DATETIME2       NOT NULL CONSTRAINT DF_dbo_HandlerSourceRawJson_auditModifiedDateUtc DEFAULT (SYSUTCDATETIME ()),

        CONSTRAINT PK_dbo_HandlerSourceRawJson PRIMARY KEY CLUSTERED (HandlerSourceId),
        CONSTRAINT CK_dbo_HandlerSourceRawJson_RawJson CHECK (RawJson IS NULL OR ISJSON (RawJson) = 1)
    )
    WITH (DATA_COMPRESSION = PAGE);
END;
GO

----------------------------------------------------------------------------------------------------
-- Foreign key to the parent version. NO ACTION on delete, not CASCADE: this database
--    performs no hard deletes, so a cascade could never fire and declaring one would
--    advertise a behaviour that does not exist.
----------------------------------------------------------------------------------------------------
IF NOT EXISTS (SELECT 1
                 FROM sys.foreign_keys
                WHERE name = N'FK_dbo_HandlerSourceRawJson_HandlerSource')
BEGIN
    ALTER TABLE dbo.HandlerSourceRawJson
        ADD CONSTRAINT FK_dbo_HandlerSourceRawJson_HandlerSource FOREIGN KEY (HandlerSourceId)
            REFERENCES dbo.HandlerSource (HandlerSourceId);
END;
GO

/*
    Extended properties. Required on the table and on EVERY column.

    Through util.uspSetObjectDescription only. It adds or updates, so this script re-runs and
    an improved wording replaces the old one; a bare sp_addextendedproperty succeeds once and
    then fails on every subsequent run.

    Each column description ends with the RCRAInfo JSON path it mirrors. Flattening turned
    siteLocation.state.code into SiteLocationStateCode, and the way back is what a reader of
    this database needs. Where EPA's spec carries no description the placeholder says so
    rather than inventing one -- a wrong description in database metadata is worse than a
    missing one.
*/

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceRawJson'
    , @Description = N'The raw EPA payload behind each dbo.HandlerSource row, one to one. Separate from the relational table so that the wide row stays narrow, and so that a scope decision reversed later can be satisfied by re-projection with no EPA re-fetch.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceRawJson'
    , @ColumnName  = N'HandlerSourceId'
    , @Description = N'The dbo.HandlerSource version this payload produced. Also the primary key: one payload per version.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceRawJson'
    , @ColumnName  = N'RawJson'
    , @Description = N'The HandlerSource JSON exactly as EPA returned it. NVARCHAR(MAX) with an ISJSON check, never the native json type, which is SQL Server 2025 only. Held in its own table so the 210-column relational row stays narrow in the buffer pool. This is what makes an omitted subtree -- the three state addenda -- recoverable by re-projection instead of by re-fetching from EPA.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceRawJson'
    , @ColumnName  = N'PayloadSha256'
    , @Description = N'SHA-256 of RawJson, hex, computed by the loader before the write. Lets an unchanged payload be recognised without comparing NVARCHAR(MAX) values, and gives the AR5 report something to point at when EPA re-issues a version with no visible change.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceRawJson'
    , @ColumnName  = N'RetrievedDateUtc'
    , @Description = N'UTC timestamp at which the loader received this payload from EPA. Distinct from auditCreatedDateUtc, which is when the row was written, and from EPA''s own SrcUpdatedDate.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceRawJson'
    , @ColumnName  = N'IsDeleted'
    , @Description = N'Soft-delete flag. 1 = deleted, 0 = active. This database performs no hard deletes; every read path filters IsDeleted = 0.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceRawJson'
    , @ColumnName  = N'auditDeletedBy'
    , @Description = N'Login that soft-deleted the row. Populated by DEFAULT on insert, so it is only meaningful when IsDeleted = 1.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceRawJson'
    , @ColumnName  = N'auditDeletedDateUtc'
    , @Description = N'UTC timestamp of the soft delete. Populated by DEFAULT on insert, so it is only meaningful when IsDeleted = 1; the deleting statement sets it explicitly.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceRawJson'
    , @ColumnName  = N'auditCreatedBy'
    , @Description = N'Login that inserted the row. Under the application logins this identifies which application wrote it, not an end user.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceRawJson'
    , @ColumnName  = N'auditCreatedDateUtc'
    , @Description = N'UTC timestamp of row insert. Set by DEFAULT; the loader omits this column from its INSERT column list so the default fires.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceRawJson'
    , @ColumnName  = N'auditModifiedBy'
    , @Description = N'Login that last modified the row.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceRawJson'
    , @ColumnName  = N'auditModifiedDateUtc'
    , @Description = N'UTC timestamp of last modification. The DEFAULT fires on INSERT only, so every UPDATE and MERGE must set this column explicitly or the audit trail will claim the row has never changed.';
GO

PRINT N'110: dbo.HandlerSourceRawJson created or altered, 11 column(s) described.';
GO
