-- Not decoration: sqlcmd defaults QUOTED_IDENTIFIER OFF where every other client defaults it ON, the
-- setting is BAKED IN at CREATE time, and a module or session carrying it OFF cannot run DML against a
-- table with a filtered index (error 1934). Every unique constraint here is one. Set it so that a hand
-- run cannot get it wrong.
SET QUOTED_IDENTIFIER ON;
GO

/**********************************************************************************************************************
ObjectName:   dbo.vwHandlerSourceHistory
Author:       generated by build/generate_schema.py
CreateDate:   2026-09-04
========================================================================================================================
Description:

Every handler source version this database holds, soft-deleted rows excluded. With EF Core reduced to calling stored
procedures, an EF Core global query filter protects nothing, so this view and dbo.vwHandlerSource are the ONLY
structural enforcement of AR7. Every consumer reads a view; a procedure that must hit the base table filters IsDeleted
= 0 itself. The four deletion-stamp columns are masked to NULL unless the row is actually deleted: auditDeletedBy and
auditDeletedDateUtc are NOT NULL with defaults, so they are populated on INSERT and would otherwise show a meaningless
deletion date beside every healthy handler in the monitoring UI.

GENERATED FILE -- do not edit by hand. Regenerate with `python build/generate_schema.py`; the column
list follows dbo.HandlerSource and would drift the moment a column is added.

========================================================================================================================
Requirements and Key Dependencies:

dbo.HandlerSource. Column-level descriptions live on that table: SQL Server
does not inherit an extended property into a view, and a second copy of 210
descriptions would drift from the first.

========================================================================================================================
Example Usage and Performance:

SELECT HandlerId, Sequence, HandlerName FROM dbo.vwHandlerSourceHistory WHERE HandlerId = N'MD0000123456' ORDER BY
Sequence DESC;

========================================================================================================================
Modification History:
Date		Author          Ticket    		Description
---------- 	--------------- -----------		----------------------------------------------------------------------------
2026-09-04	generated						Initial version. Workstream B1.
**********************************************************************************************************************/

CREATE OR ALTER VIEW dbo.vwHandlerSourceHistory
AS
SELECT
       hs.HandlerSourceId
       , hs.HandlerId
       , hs.ActivityLocation
       , hs.SourceType
       , hs.Sequence
       , hs.SourceTypeDescription
       , hs.SourceTypeSortOrder
       , hs.CurrentRecord
       , hs.ExtractFlag
       , hs.ReceivedDate
       , hs.HandlerName
       , hs.NonNotifierCode
       , hs.NonNotifierDescription
       , hs.Acknowledgement
       , hs.AccessibilityCode
       , hs.AccessibilityDescription
       , hs.SiteLocationStreetNumber
       , hs.SiteLocationAddress1
       , hs.SiteLocationAddress2
       , hs.SiteLocationCity
       , hs.SiteLocationStateActivityLocation
       , hs.SiteLocationStateCode
       , hs.SiteLocationStateDescription
       , hs.SiteLocationStateActive
       , hs.SiteLocationForeignStateActivityLocation
       , hs.SiteLocationForeignStateCode
       , hs.SiteLocationForeignStateDescription
       , hs.SiteLocationForeignStateActive
       , hs.SiteLocationForeignStateName
       , hs.SiteLocationForeignStateCountryCode
       , hs.SiteLocationCountryActivityLocation
       , hs.SiteLocationCountryCode
       , hs.SiteLocationCountryDescription
       , hs.SiteLocationCountryActive
       , hs.SiteLocationZip
       , hs.SiteLocationLatitude
       , hs.SiteLocationLongitude
       , hs.SiteLocationLatLongPrimary
       , hs.SiteLocationGisOriginActivityLocation
       , hs.SiteLocationGisOriginCode
       , hs.SiteLocationGisOriginDescription
       , hs.SiteLocationGisOriginActive
       , hs.SiteLocationCountyActivityLocation
       , hs.SiteLocationCountyCode
       , hs.SiteLocationCountyDescription
       , hs.SiteLocationCountyActive
       , hs.SiteLocationStateDistrictActivityLocation
       , hs.SiteLocationStateDistrictCode
       , hs.SiteLocationStateDistrictDescription
       , hs.SiteLocationStateDistrictActive
       , hs.SiteLocationStandardized
       , hs.LandTypeCode
       , hs.LandTypeDescription
       , hs.SiteMailingAddressStreetNumber
       , hs.SiteMailingAddressAddress1
       , hs.SiteMailingAddressAddress2
       , hs.SiteMailingAddressCity
       , hs.SiteMailingAddressStateActivityLocation
       , hs.SiteMailingAddressStateCode
       , hs.SiteMailingAddressStateDescription
       , hs.SiteMailingAddressStateActive
       , hs.SiteMailingAddressForeignStateActivityLocation
       , hs.SiteMailingAddressForeignStateCode
       , hs.SiteMailingAddressForeignStateDescription
       , hs.SiteMailingAddressForeignStateActive
       , hs.SiteMailingAddressForeignStateName
       , hs.SiteMailingAddressForeignStateCountryCode
       , hs.SiteMailingAddressCountryActivityLocation
       , hs.SiteMailingAddressCountryCode
       , hs.SiteMailingAddressCountryDescription
       , hs.SiteMailingAddressCountryActive
       , hs.SiteMailingAddressZip
       , hs.NaicsPrimaryActivityLocation
       , hs.NaicsPrimaryCode
       , hs.NaicsPrimaryDescription
       , hs.NaicsPrimaryActive
       , hs.ContactFirstName
       , hs.ContactMiddleInitial
       , hs.ContactLastName
       , hs.ContactTitle
       , hs.ContactPhone
       , hs.ContactPhoneExtension
       , hs.ContactFax
       , hs.ContactEmail
       , hs.ContactLanguageActivityLocation
       , hs.ContactLanguageCode
       , hs.ContactLanguageDescription
       , hs.ContactLanguageActive
       , hs.ContactAddressStreetNumber
       , hs.ContactAddressAddress1
       , hs.ContactAddressAddress2
       , hs.ContactAddressCity
       , hs.ContactAddressStateActivityLocation
       , hs.ContactAddressStateCode
       , hs.ContactAddressStateDescription
       , hs.ContactAddressStateActive
       , hs.ContactAddressForeignStateActivityLocation
       , hs.ContactAddressForeignStateCode
       , hs.ContactAddressForeignStateDescription
       , hs.ContactAddressForeignStateActive
       , hs.ContactAddressForeignStateName
       , hs.ContactAddressForeignStateCountryCode
       , hs.ContactAddressCountryActivityLocation
       , hs.ContactAddressCountryCode
       , hs.ContactAddressCountryDescription
       , hs.ContactAddressCountryActive
       , hs.ContactAddressZip
       , hs.WasteFederalGeneratorCategoryActivityLocation
       , hs.WasteFederalGeneratorCategoryCode
       , hs.WasteFederalGeneratorCategoryDescription
       , hs.WasteFederalGeneratorCategoryActive
       , hs.WasteStateGeneratorCategoryActivityLocation
       , hs.WasteStateGeneratorCategoryCode
       , hs.WasteStateGeneratorCategoryDescription
       , hs.WasteStateGeneratorCategoryActive
       , hs.WasteFurnaceExemption
       , hs.WasteMixedWasteGenerator
       , hs.WasteOnsiteBurnerExemption
       , hs.WasteReceivesOffSite
       , hs.WasteRecognizedTraderExporter
       , hs.WasteRecognizedTraderImporter
       , hs.WasteRecyclerActivity
       , hs.WasteRecyclerActivityNonStorage
       , hs.WasteShortTermGenerator
       , hs.WasteShortTermGeneratorNotes
       , hs.WasteSlabExporter
       , hs.WasteSlabImporter
       , hs.WasteSubPartKCollege
       , hs.WasteSubPartKHospital
       , hs.WasteSubPartKNonprofit
       , hs.WasteSubPartKWithdrawal
       , hs.WasteSubPartPHealthCare
       , hs.WasteSubPartPReverseDistributor
       , hs.WasteSubPartPWithdrawal
       , hs.WasteTransferFacility
       , hs.WasteTransporter
       , hs.WasteTsd
       , hs.WasteUndergroundInjectionControl
       , hs.WasteUniversalWasteDestinationFacility
       , hs.WasteUsImporter
       , hs.WasteUsedOilBurner
       , hs.WasteUsedOilMarketBurner
       , hs.WasteUsedOilProcessor
       , hs.WasteUsedOilRefiner
       , hs.WasteUsedOilSpecMarketer
       , hs.WasteUsedOilTransferFacility
       , hs.WasteUsedOilTransporter
       , hs.PermitContactFirstName
       , hs.PermitContactMiddleInitial
       , hs.PermitContactLastName
       , hs.PermitContactTitle
       , hs.PermitContactPhone
       , hs.PermitContactPhoneExtension
       , hs.PermitContactEmail
       , hs.PermitContactAddressStreetNumber
       , hs.PermitContactAddressAddress1
       , hs.PermitContactAddressAddress2
       , hs.PermitContactAddressCity
       , hs.PermitContactAddressStateActivityLocation
       , hs.PermitContactAddressStateCode
       , hs.PermitContactAddressStateDescription
       , hs.PermitContactAddressStateActive
       , hs.PermitContactAddressForeignStateActivityLocation
       , hs.PermitContactAddressForeignStateCode
       , hs.PermitContactAddressForeignStateDescription
       , hs.PermitContactAddressForeignStateActive
       , hs.PermitContactAddressForeignStateName
       , hs.PermitContactAddressForeignStateCountryCode
       , hs.PermitContactAddressCountryActivityLocation
       , hs.PermitContactAddressCountryCode
       , hs.PermitContactAddressCountryDescription
       , hs.PermitContactAddressCountryActive
       , hs.PermitContactAddressZip
       , hs.PermitFacilityExistenceDate
       , hs.PermitNatureOfBusiness
       , hs.HsmManaged
       , hs.HsmFinancialAssurance
       , hs.HsmReasonCode
       , hs.HsmReasonDescription
       , hs.HsmEffectiveDate
       , hs.LqgSiteClosureCompliance
       , hs.LqgSiteClosureExpectedClosureDate
       , hs.LqgSiteClosureRequestedClosureDate
       , hs.LqgSiteClosureDateClosed
       , hs.LqgSiteClosureClosureTypeCode
       , hs.LqgSiteClosureClosureTypeDescription
       , hs.EpisodicEventTypeActivityLocation
       , hs.EpisodicEventTypeCode
       , hs.EpisodicEventTypeDescription
       , hs.EpisodicEventTypeActive
       , hs.EpisodicContactFirstName
       , hs.EpisodicContactMiddleInitial
       , hs.EpisodicContactLastName
       , hs.EpisodicContactPhone
       , hs.EpisodicContactPhoneExt
       , hs.EpisodicContactEmail
       , hs.EpisodicBeginDate
       , hs.EpisodicEndDate
       , hs.EpisodicRescind
       , hs.EpisodicRescindComment
       , hs.Comments
       , hs.PublicComments
       , hs.SrcUpdatedDate
       , hs.SrcUpdatedBy
       , hs.SrcCreatedDate
       , hs.SrcCreatedBy
       , hs.LastRecord
       , hs.ElectronicManifestBroker
       , hs.BrExempt
       , hs.IncludeInNationalReport
       , hs.ReportCycle
     , hs.IsDeleted
       -- Masked: both columns are NOT NULL with a DEFAULT, so they carry an insert-time
       -- value on every live row. NULL is the honest answer for a row that is not deleted.
     , CASE WHEN hs.IsDeleted = 1 THEN hs.auditDeletedBy      END AS auditDeletedBy
     , CASE WHEN hs.IsDeleted = 1 THEN hs.auditDeletedDateUtc END AS auditDeletedDateUtc
     , hs.auditCreatedBy
     , hs.auditCreatedDateUtc
     , hs.auditModifiedBy
     , hs.auditModifiedDateUtc
  FROM dbo.HandlerSource AS hs
 WHERE hs.IsDeleted = 0;
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'VIEW'
    , @ObjectName  = N'vwHandlerSourceHistory'
    , @Description = N'Every handler source version held, soft-deleted rows excluded. One of the two AR7 enforcement points; with EF Core calling only procedures, these views are the only structural guarantee that IsDeleted = 0 is applied. Deletion-stamp columns read NULL unless the row is deleted.';
GO

PRINT N'120: dbo.vwHandlerSourceHistory created or altered.';
GO
