-- Not decoration: sqlcmd defaults QUOTED_IDENTIFIER OFF where every other client defaults it ON, the
-- setting is BAKED IN at CREATE time, and a module or session carrying it OFF cannot run DML against a
-- table with a filtered index (error 1934). Every unique constraint here is one. Set it so that a hand
-- run cannot get it wrong.
SET QUOTED_IDENTIFIER ON;
GO

/**********************************************************************************************************************
ObjectName:   dbo.vwHandlerSource
Author:       generated by build/generate_schema.py
CreateDate:   2026-09-04
========================================================================================================================
Description:

The current version of each handler source record: soft-deleted rows excluded and CurrentRecord = 1. This is the
default read path for the application. It selects from dbo.vwHandlerSourceHistory rather than from the base table, so
the IsDeleted filter and the deletion-stamp masking are defined once and the two views cannot disagree.

GENERATED FILE -- do not edit by hand. Regenerate with `python build/generate_schema.py`; the column
list follows dbo.HandlerSource and would drift the moment a column is added.

========================================================================================================================
Requirements and Key Dependencies:

dbo.HandlerSource. Column-level descriptions live on that table: SQL Server
does not inherit an extended property into a view, and a second copy of 210
descriptions would drift from the first.

========================================================================================================================
Example Usage and Performance:

SELECT HandlerId, HandlerName, ActivityLocation FROM dbo.vwHandlerSource WHERE ActivityLocation = N'MD';

========================================================================================================================
Modification History:
Date		Author          Ticket    		Description
---------- 	--------------- -----------		----------------------------------------------------------------------------
2026-09-04	generated						Initial version. Workstream B1.
**********************************************************************************************************************/

CREATE OR ALTER VIEW dbo.vwHandlerSource
AS
SELECT *
  FROM dbo.vwHandlerSourceHistory
 WHERE CurrentRecord = 1;
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'VIEW'
    , @ObjectName  = N'vwHandlerSource'
    , @Description = N'The current version of each handler source record: IsDeleted = 0 and CurrentRecord = 1. The default read path for the applications. Layered on dbo.vwHandlerSourceHistory so the AR7 filter is defined in exactly one place.';
GO

PRINT N'121: dbo.vwHandlerSource created or altered.';
GO
