/**********************************************************************************************************************
Script:       130_dbo.HandlerSourceAdditionalContact.sql
Author:       generated by build/generate_schema.py
========================================================================================================================
Description:

Mirrors the RCRAInfo additionalContacts collection -- an array of objects with 35 leaf field(s) -- one row per
element. Keyed to dbo.HandlerSource by surrogate key and ordered by OrdinalPosition.

GENERATED FILE -- do not edit by hand. Regenerate with:

    python build/generate_schema.py

Generated from one repeating collection in EPA's HandlerSource payload.

build/guardrails.py runs `generate_schema.py --check`, which fails if this file and the spec
have drifted apart, so editing it here is not merely discouraged -- it breaks the build.

========================================================================================================================
Notes:

RE-RUNNABLE. Every CREATE is guarded, descriptions go through util.uspSetObjectDescription
(which adds or updates), and nothing is dropped or truncated. A second run changes nothing.

Later changes are ADDITIVE: append a guarded ALTER TABLE ... ADD block rather than editing
the CREATE TABLE above, or the script stops converging on a database that already has the
table. In this file that means changing the generator, not the output.
**********************************************************************************************************************/

SET XACT_ABORT ON;
-- Not decoration: sqlcmd defaults QUOTED_IDENTIFIER OFF where every other client defaults it ON, the
-- setting is BAKED IN at CREATE time, and a module or session carrying it OFF cannot run DML against a
-- table with a filtered index (error 1934). Every unique constraint here is one. Set it so that a hand
-- run cannot get it wrong.
SET QUOTED_IDENTIFIER ON;
GO

----------------------------------------------------------------------------------------------------
-- 1. The table. Guarded, so a second run is a no-op.
----------------------------------------------------------------------------------------------------
IF OBJECT_ID (N'dbo.HandlerSourceAdditionalContact', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.HandlerSourceAdditionalContact
    (
        HandlerSourceAdditionalContactId     INT             IDENTITY (1, 1) NOT NULL,
        HandlerSourceId                      INT                             NOT NULL,
        OrdinalPosition                      INT                             NOT NULL,
        FirstName                            NVARCHAR (38)                       NULL,
        MiddleInitial                        NVARCHAR (1)                        NULL,
        LastName                             NVARCHAR (38)                       NULL,
        Title                                NVARCHAR (45)                       NULL,
        Phone                                NVARCHAR (15)                       NULL,
        PhoneExtension                       NVARCHAR (6)                        NULL,
        Fax                                  NVARCHAR (15)                       NULL,
        Email                                NVARCHAR (80)                       NULL,
        LanguageActivityLocation             NVARCHAR (2)                        NULL,
        LanguageCode                         NVARCHAR (2)                        NULL,
        LanguageDescription                  NVARCHAR (255)                      NULL,
        LanguageActive                       BIT                                 NULL,
        AddressStreetNumber                  NVARCHAR (12)                       NULL,
        AddressAddress1                      NVARCHAR (50)                       NULL,
        AddressAddress2                      NVARCHAR (50)                       NULL,
        AddressCity                          NVARCHAR (25)                       NULL,
        AddressStateActivityLocation         NVARCHAR (2)                        NULL,
        AddressStateCode                     NVARCHAR (2)                        NULL,
        AddressStateDescription              NVARCHAR (255)                      NULL,
        AddressStateActive                   BIT                                 NULL,
        AddressForeignStateActivityLocation  NVARCHAR (2)                        NULL,
        AddressForeignStateCode              NVARCHAR (2)                        NULL,
        AddressForeignStateDescription       NVARCHAR (255)                      NULL,
        AddressForeignStateActive            BIT                                 NULL,
        AddressForeignStateName              NVARCHAR (80)                       NULL,
        AddressForeignStateCountryCode       NVARCHAR (2)                        NULL,
        AddressCountryActivityLocation       NVARCHAR (2)                        NULL,
        AddressCountryCode                   NVARCHAR (2)                        NULL,
        AddressCountryDescription            NVARCHAR (255)                      NULL,
        AddressCountryActive                 BIT                                 NULL,
        AddressZip                           NVARCHAR (14)                       NULL,
        TypeActivityLocation                 NVARCHAR (2)                        NULL,
        SourceType                           NVARCHAR (2)                        NULL,
        SourceTypeDescription                NVARCHAR (255)                      NULL,
        TypeActive                           BIT                                 NULL,
        IsDeleted                            BIT                             NOT NULL CONSTRAINT DF_dbo_HandlerSourceAdditionalContact_IsDeleted DEFAULT (0),
        auditDeletedBy                       NVARCHAR (128)                  NOT NULL CONSTRAINT DF_dbo_HandlerSourceAdditionalContact_auditDeletedBy DEFAULT (ORIGINAL_LOGIN ()),
        auditDeletedDateUtc                  DATETIME2                       NOT NULL CONSTRAINT DF_dbo_HandlerSourceAdditionalContact_auditDeletedDateUtc DEFAULT (SYSUTCDATETIME ()),
        auditCreatedBy                       NVARCHAR (128)                  NOT NULL CONSTRAINT DF_dbo_HandlerSourceAdditionalContact_auditCreatedBy DEFAULT (ORIGINAL_LOGIN ()),
        auditCreatedDateUtc                  DATETIME2                       NOT NULL CONSTRAINT DF_dbo_HandlerSourceAdditionalContact_auditCreatedDateUtc DEFAULT (SYSUTCDATETIME ()),
        auditModifiedBy                      NVARCHAR (128)                  NOT NULL CONSTRAINT DF_dbo_HandlerSourceAdditionalContact_auditModifiedBy DEFAULT (ORIGINAL_LOGIN ()),
        auditModifiedDateUtc                 DATETIME2                       NOT NULL CONSTRAINT DF_dbo_HandlerSourceAdditionalContact_auditModifiedDateUtc DEFAULT (SYSUTCDATETIME ()),

        CONSTRAINT PK_dbo_HandlerSourceAdditionalContact PRIMARY KEY CLUSTERED (HandlerSourceAdditionalContactId)
    )
    WITH (DATA_COMPRESSION = PAGE);
END;
GO

----------------------------------------------------------------------------------------------------
-- 2. Natural key.
--    A filtered unique index, not a unique constraint: a soft-deleted row keeps its key,
--    and an unfiltered constraint would block re-creation of that key forever -- the load
--    would fail on a handler EPA had corrected and resubmitted.
----------------------------------------------------------------------------------------------------
IF NOT EXISTS (SELECT 1
                 FROM sys.indexes
                WHERE name      = N'UX_dbo_HandlerSourceAdditionalContact_Natural'
                  AND object_id = OBJECT_ID (N'dbo.HandlerSourceAdditionalContact'))
BEGIN
    CREATE UNIQUE INDEX UX_dbo_HandlerSourceAdditionalContact_Natural
        ON dbo.HandlerSourceAdditionalContact (HandlerSourceId, OrdinalPosition)
        WHERE IsDeleted = 0
        WITH (DATA_COMPRESSION = PAGE);
END;
GO

IF EXISTS (SELECT 1
             FROM sys.indexes AS i
             JOIN sys.partitions AS p
               ON p.object_id = i.object_id
              AND p.index_id  = i.index_id
            WHERE i.name      = N'UX_dbo_HandlerSourceAdditionalContact_Natural'
              AND i.object_id = OBJECT_ID (N'dbo.HandlerSourceAdditionalContact')
              AND p.data_compression_desc <> N'PAGE')
BEGIN
    ALTER INDEX UX_dbo_HandlerSourceAdditionalContact_Natural
        ON dbo.HandlerSourceAdditionalContact REBUILD WITH (DATA_COMPRESSION = PAGE);
END;
GO

----------------------------------------------------------------------------------------------------
-- 3. The foreign key column.
--    Deliberately NOT redundant with UX_dbo_HandlerSourceAdditionalContact_Natural above. That index is filtered to
--    IsDeleted = 0, so it cannot serve a lookup that has to see soft-deleted rows -- and
--    for this loader that is a normal path, not an exceptional one. Nothing is ever hard-
--    deleted, so re-loading a handler means finding the existing child rows, including any
--    previously soft-deleted, and reviving them. Without this index that seek is a scan of
--    every child row in the table, for every handler in the batch.
----------------------------------------------------------------------------------------------------
IF NOT EXISTS (SELECT 1
                 FROM sys.indexes
                WHERE name      = N'IX_dbo_HandlerSourceAdditionalContact_HandlerSourceId'
                  AND object_id = OBJECT_ID (N'dbo.HandlerSourceAdditionalContact'))
BEGIN
    CREATE INDEX IX_dbo_HandlerSourceAdditionalContact_HandlerSourceId
        ON dbo.HandlerSourceAdditionalContact (HandlerSourceId)
        WITH (DATA_COMPRESSION = PAGE);
END;
GO

IF EXISTS (SELECT 1
             FROM sys.indexes AS i
             JOIN sys.partitions AS p
               ON p.object_id = i.object_id
              AND p.index_id  = i.index_id
            WHERE i.name      = N'IX_dbo_HandlerSourceAdditionalContact_HandlerSourceId'
              AND i.object_id = OBJECT_ID (N'dbo.HandlerSourceAdditionalContact')
              AND p.data_compression_desc <> N'PAGE')
BEGIN
    ALTER INDEX IX_dbo_HandlerSourceAdditionalContact_HandlerSourceId
        ON dbo.HandlerSourceAdditionalContact REBUILD WITH (DATA_COMPRESSION = PAGE);
END;
GO

----------------------------------------------------------------------------------------------------
-- Foreign key to the parent version. NO ACTION on delete, not CASCADE: this database
--    performs no hard deletes, so a cascade could never fire and declaring one would
--    advertise a behaviour that does not exist.
----------------------------------------------------------------------------------------------------
IF NOT EXISTS (SELECT 1
                 FROM sys.foreign_keys
                WHERE name = N'FK_dbo_HandlerSourceAdditionalContact_HandlerSource')
BEGIN
    ALTER TABLE dbo.HandlerSourceAdditionalContact
        ADD CONSTRAINT FK_dbo_HandlerSourceAdditionalContact_HandlerSource FOREIGN KEY (HandlerSourceId)
            REFERENCES dbo.HandlerSource (HandlerSourceId);
END;
GO

/*
    Extended properties. Required on the table and on EVERY column.

    Through util.uspSetObjectDescription only. It adds or updates, so this script re-runs and
    an improved wording replaces the old one; a bare sp_addextendedproperty succeeds once and
    then fails on every subsequent run.

    Each column description ends with the RCRAInfo JSON path it mirrors. Flattening turned
    siteLocation.state.code into SiteLocationStateCode, and the way back is what a reader of
    this database needs. Where EPA's spec carries no description the placeholder says so
    rather than inventing one -- a wrong description in database metadata is worse than a
    missing one.
*/

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @Description = N'Mirrors the RCRAInfo additionalContacts collection -- an array of objects with 35 leaf field(s) -- one row per element. Keyed to dbo.HandlerSource by surrogate key and ordered by OrdinalPosition.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'HandlerSourceAdditionalContactId'
    , @Description = N'Surrogate key for one element of the RCRAInfo additionalContacts array.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'HandlerSourceId'
    , @Description = N'The dbo.HandlerSource version this row belongs to. Keyed to the surrogate key, never to HandlerId: keying a collection to HandlerId collapses every version of the handler into one list and corrupts the history.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'OrdinalPosition'
    , @Description = N'Zero-based position of this element within the RCRAInfo additionalContacts array. A JSON array is ordered, and EPA supplies no key for these elements, so the position is both the fidelity of the mirror and the only natural key this row has.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'FirstName'
    , @Description = N'First name of the primary contact person for the site location who should be reasonably expected to be available at all times and fully aware of the regulated activities being performed at the site. [RCRAInfo: additionalContacts[].firstName]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'MiddleInitial'
    , @Description = N'Middle initial of the primary contact person for the site location who should be reasonably expected to be available at all times and fully aware of the regulated activities being performed at the site. [RCRAInfo: additionalContacts[].middleInitial]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'LastName'
    , @Description = N'Last name of the primary contact person for the site location who should be reasonably expected to be available at all times and fully aware of the regulated activities being performed at the site. [RCRAInfo: additionalContacts[].lastName]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'Title'
    , @Description = N'Title of the site contact person. [RCRAInfo: additionalContacts[].title]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'Phone'
    , @Description = N'Telephone number at which the site contact may be reached. Note: Phonenumbers associated with US addresses may be formatted as 9999999999 or 999-999-9999 but will be stored in the database as 999-999-9999. [RCRAInfo: additionalContacts[].phone]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'PhoneExtension'
    , @Description = N'Extension of the telephone number at which the site contact may be reached. [RCRAInfo: additionalContacts[].phoneExtension]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'Fax'
    , @Description = N'Facsimile number at which the site contact may be reached. Note: Fax numbers associated with US addresses may be formatted as 9999999999 or 999-999-9999 but will be stored in the database as 999-999-9999. [RCRAInfo: additionalContacts[].fax]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'Email'
    , @Description = N'Email address associated with the contact. [RCRAInfo: additionalContacts[].email]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'LanguageActivityLocation'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: additionalContacts[].language.activityLocation]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'LanguageCode'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: additionalContacts[].language.code]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'LanguageDescription'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: additionalContacts[].language.description]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'LanguageActive'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: additionalContacts[].language.active]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'AddressStreetNumber'
    , @Description = N'The street number from the contact street address. [RCRAInfo: additionalContacts[].address.streetNumber]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'AddressAddress1'
    , @Description = N'First line of the street address (or the post office box number) for the contact. [RCRAInfo: additionalContacts[].address.address1]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'AddressAddress2'
    , @Description = N'Second line (as needed) of the street address for the contact. [RCRAInfo: additionalContacts[].address.address2]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'AddressCity'
    , @Description = N'The city or town of the contact address. [RCRAInfo: additionalContacts[].address.city]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'AddressStateActivityLocation'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: additionalContacts[].address.state.activityLocation]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'AddressStateCode'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: additionalContacts[].address.state.code]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'AddressStateDescription'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: additionalContacts[].address.state.description]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'AddressStateActive'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: additionalContacts[].address.state.active]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'AddressForeignStateActivityLocation'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: additionalContacts[].address.foreignState.activityLocation]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'AddressForeignStateCode'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: additionalContacts[].address.foreignState.code]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'AddressForeignStateDescription'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: additionalContacts[].address.foreignState.description]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'AddressForeignStateActive'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: additionalContacts[].address.foreignState.active]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'AddressForeignStateName'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: additionalContacts[].address.foreignState.name]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'AddressForeignStateCountryCode'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: additionalContacts[].address.foreignState.countryCode]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'AddressCountryActivityLocation'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: additionalContacts[].address.country.activityLocation]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'AddressCountryCode'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: additionalContacts[].address.country.code]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'AddressCountryDescription'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: additionalContacts[].address.country.description]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'AddressCountryActive'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: additionalContacts[].address.country.active]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'AddressZip'
    , @Description = N'Zip code of the contact address. Note: Zip codes associated with US addresses may be formatted as 99999, 999999999, or 99999-9999 but will be stored in the database as 99999 or 99999-9999. [RCRAInfo: additionalContacts[].address.zip]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'TypeActivityLocation'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: additionalContacts[].type.activityLocation]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'SourceType'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: additionalContacts[].type.code]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'SourceTypeDescription'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: additionalContacts[].type.description]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'TypeActive'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: additionalContacts[].type.active]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'IsDeleted'
    , @Description = N'Soft-delete flag. 1 = deleted, 0 = active. This database performs no hard deletes; every read path filters IsDeleted = 0.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'auditDeletedBy'
    , @Description = N'Login that soft-deleted the row. Populated by DEFAULT on insert, so it is only meaningful when IsDeleted = 1.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'auditDeletedDateUtc'
    , @Description = N'UTC timestamp of the soft delete. Populated by DEFAULT on insert, so it is only meaningful when IsDeleted = 1; the deleting statement sets it explicitly.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'auditCreatedBy'
    , @Description = N'Login that inserted the row. Under the application logins this identifies which application wrote it, not an end user.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'auditCreatedDateUtc'
    , @Description = N'UTC timestamp of row insert. Set by DEFAULT; the loader omits this column from its INSERT column list so the default fires.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'auditModifiedBy'
    , @Description = N'Login that last modified the row.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceAdditionalContact'
    , @ColumnName  = N'auditModifiedDateUtc'
    , @Description = N'UTC timestamp of last modification. The DEFAULT fires on INSERT only, so every UPDATE and MERGE must set this column explicitly or the audit trail will claim the row has never changed.';
GO

PRINT N'130: dbo.HandlerSourceAdditionalContact created or altered, 45 column(s) described.';
GO
