/**********************************************************************************************************************
Script:       131_dbo.HandlerSourceOwner.sql
Author:       generated by build/generate_schema.py
========================================================================================================================
Description:

Mirrors the RCRAInfo owners collection -- an array of objects with 30 leaf field(s) -- one row per element. Keyed to
dbo.HandlerSource by surrogate key and ordered by OrdinalPosition.

GENERATED FILE -- do not edit by hand. Regenerate with:

    python build/generate_schema.py

Generated from one repeating collection in EPA's HandlerSource payload.

build/guardrails.py runs `generate_schema.py --check`, which fails if this file and the spec
have drifted apart, so editing it here is not merely discouraged -- it breaks the build.

========================================================================================================================
Notes:

RE-RUNNABLE. Every CREATE is guarded, descriptions go through util.uspSetObjectDescription
(which adds or updates), and nothing is dropped or truncated. A second run changes nothing.

Later changes are ADDITIVE: append a guarded ALTER TABLE ... ADD block rather than editing
the CREATE TABLE above, or the script stops converging on a database that already has the
table. In this file that means changing the generator, not the output.
**********************************************************************************************************************/

SET XACT_ABORT ON;
-- Not decoration: sqlcmd defaults QUOTED_IDENTIFIER OFF where every other client defaults it ON, the
-- setting is BAKED IN at CREATE time, and a module or session carrying it OFF cannot run DML against a
-- table with a filtered index (error 1934). Every unique constraint here is one. Set it so that a hand
-- run cannot get it wrong.
SET QUOTED_IDENTIFIER ON;
GO

----------------------------------------------------------------------------------------------------
-- 1. The table. Guarded, so a second run is a no-op.
----------------------------------------------------------------------------------------------------
IF OBJECT_ID (N'dbo.HandlerSourceOwner', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.HandlerSourceOwner
    (
        HandlerSourceOwnerId                 INT              IDENTITY (1, 1) NOT NULL,
        HandlerSourceId                      INT                              NOT NULL,
        OrdinalPosition                      INT                              NOT NULL,
        Name                                 NVARCHAR (80)                        NULL,
        Phone                                NVARCHAR (15)                        NULL,
        PhoneExtension                       NVARCHAR (6)                         NULL,
        Email                                NVARCHAR (80)                        NULL,
        Fax                                  NVARCHAR (15)                        NULL,
        BecameCurrent                        DATE                                 NULL,
        EndedCurrent                         DATE                                 NULL,
        AddressStreetNumber                  NVARCHAR (12)                        NULL,
        AddressAddress1                      NVARCHAR (50)                        NULL,
        AddressAddress2                      NVARCHAR (50)                        NULL,
        AddressCity                          NVARCHAR (25)                        NULL,
        AddressStateActivityLocation         NVARCHAR (2)                         NULL,
        AddressStateCode                     NVARCHAR (2)                         NULL,
        AddressStateDescription              NVARCHAR (255)                       NULL,
        AddressStateActive                   BIT                                  NULL,
        AddressForeignStateActivityLocation  NVARCHAR (2)                         NULL,
        AddressForeignStateCode              NVARCHAR (2)                         NULL,
        AddressForeignStateDescription       NVARCHAR (255)                       NULL,
        AddressForeignStateActive            BIT                                  NULL,
        AddressForeignStateName              NVARCHAR (80)                        NULL,
        AddressForeignStateCountryCode       NVARCHAR (2)                         NULL,
        AddressCountryActivityLocation       NVARCHAR (2)                         NULL,
        AddressCountryCode                   NVARCHAR (2)                         NULL,
        AddressCountryDescription            NVARCHAR (255)                       NULL,
        AddressCountryActive                 BIT                                  NULL,
        AddressZip                           NVARCHAR (14)                        NULL,
        SourceType                           NVARCHAR (1)                         NULL,
        SourceTypeDescription                NVARCHAR (255)                       NULL,
        Notes                                NVARCHAR (4000)                      NULL,
        PublicNotes                          NVARCHAR (4000)                      NULL,
        IsDeleted                            BIT                              NOT NULL CONSTRAINT DF_dbo_HandlerSourceOwner_IsDeleted DEFAULT (0),
        auditDeletedBy                       NVARCHAR (128)                   NOT NULL CONSTRAINT DF_dbo_HandlerSourceOwner_auditDeletedBy DEFAULT (ORIGINAL_LOGIN ()),
        auditDeletedDateUtc                  DATETIME2                        NOT NULL CONSTRAINT DF_dbo_HandlerSourceOwner_auditDeletedDateUtc DEFAULT (SYSUTCDATETIME ()),
        auditCreatedBy                       NVARCHAR (128)                   NOT NULL CONSTRAINT DF_dbo_HandlerSourceOwner_auditCreatedBy DEFAULT (ORIGINAL_LOGIN ()),
        auditCreatedDateUtc                  DATETIME2                        NOT NULL CONSTRAINT DF_dbo_HandlerSourceOwner_auditCreatedDateUtc DEFAULT (SYSUTCDATETIME ()),
        auditModifiedBy                      NVARCHAR (128)                   NOT NULL CONSTRAINT DF_dbo_HandlerSourceOwner_auditModifiedBy DEFAULT (ORIGINAL_LOGIN ()),
        auditModifiedDateUtc                 DATETIME2                        NOT NULL CONSTRAINT DF_dbo_HandlerSourceOwner_auditModifiedDateUtc DEFAULT (SYSUTCDATETIME ()),

        CONSTRAINT PK_dbo_HandlerSourceOwner PRIMARY KEY CLUSTERED (HandlerSourceOwnerId)
    )
    WITH (DATA_COMPRESSION = PAGE);
END;
GO

----------------------------------------------------------------------------------------------------
-- 2. Natural key.
--    A filtered unique index, not a unique constraint: a soft-deleted row keeps its key,
--    and an unfiltered constraint would block re-creation of that key forever -- the load
--    would fail on a handler EPA had corrected and resubmitted.
----------------------------------------------------------------------------------------------------
IF NOT EXISTS (SELECT 1
                 FROM sys.indexes
                WHERE name      = N'UX_dbo_HandlerSourceOwner_Natural'
                  AND object_id = OBJECT_ID (N'dbo.HandlerSourceOwner'))
BEGIN
    CREATE UNIQUE INDEX UX_dbo_HandlerSourceOwner_Natural
        ON dbo.HandlerSourceOwner (HandlerSourceId, OrdinalPosition)
        WHERE IsDeleted = 0
        WITH (DATA_COMPRESSION = PAGE);
END;
GO

IF EXISTS (SELECT 1
             FROM sys.indexes AS i
             JOIN sys.partitions AS p
               ON p.object_id = i.object_id
              AND p.index_id  = i.index_id
            WHERE i.name      = N'UX_dbo_HandlerSourceOwner_Natural'
              AND i.object_id = OBJECT_ID (N'dbo.HandlerSourceOwner')
              AND p.data_compression_desc <> N'PAGE')
BEGIN
    ALTER INDEX UX_dbo_HandlerSourceOwner_Natural
        ON dbo.HandlerSourceOwner REBUILD WITH (DATA_COMPRESSION = PAGE);
END;
GO

----------------------------------------------------------------------------------------------------
-- 3. The foreign key column.
--    Deliberately NOT redundant with UX_dbo_HandlerSourceOwner_Natural above. That index is filtered to
--    IsDeleted = 0, so it cannot serve a lookup that has to see soft-deleted rows -- and
--    for this loader that is a normal path, not an exceptional one. Nothing is ever hard-
--    deleted, so re-loading a handler means finding the existing child rows, including any
--    previously soft-deleted, and reviving them. Without this index that seek is a scan of
--    every child row in the table, for every handler in the batch.
----------------------------------------------------------------------------------------------------
IF NOT EXISTS (SELECT 1
                 FROM sys.indexes
                WHERE name      = N'IX_dbo_HandlerSourceOwner_HandlerSourceId'
                  AND object_id = OBJECT_ID (N'dbo.HandlerSourceOwner'))
BEGIN
    CREATE INDEX IX_dbo_HandlerSourceOwner_HandlerSourceId
        ON dbo.HandlerSourceOwner (HandlerSourceId)
        WITH (DATA_COMPRESSION = PAGE);
END;
GO

IF EXISTS (SELECT 1
             FROM sys.indexes AS i
             JOIN sys.partitions AS p
               ON p.object_id = i.object_id
              AND p.index_id  = i.index_id
            WHERE i.name      = N'IX_dbo_HandlerSourceOwner_HandlerSourceId'
              AND i.object_id = OBJECT_ID (N'dbo.HandlerSourceOwner')
              AND p.data_compression_desc <> N'PAGE')
BEGIN
    ALTER INDEX IX_dbo_HandlerSourceOwner_HandlerSourceId
        ON dbo.HandlerSourceOwner REBUILD WITH (DATA_COMPRESSION = PAGE);
END;
GO

----------------------------------------------------------------------------------------------------
-- Foreign key to the parent version. NO ACTION on delete, not CASCADE: this database
--    performs no hard deletes, so a cascade could never fire and declaring one would
--    advertise a behaviour that does not exist.
----------------------------------------------------------------------------------------------------
IF NOT EXISTS (SELECT 1
                 FROM sys.foreign_keys
                WHERE name = N'FK_dbo_HandlerSourceOwner_HandlerSource')
BEGIN
    ALTER TABLE dbo.HandlerSourceOwner
        ADD CONSTRAINT FK_dbo_HandlerSourceOwner_HandlerSource FOREIGN KEY (HandlerSourceId)
            REFERENCES dbo.HandlerSource (HandlerSourceId);
END;
GO

/*
    Extended properties. Required on the table and on EVERY column.

    Through util.uspSetObjectDescription only. It adds or updates, so this script re-runs and
    an improved wording replaces the old one; a bare sp_addextendedproperty succeeds once and
    then fails on every subsequent run.

    Each column description ends with the RCRAInfo JSON path it mirrors. Flattening turned
    siteLocation.state.code into SiteLocationStateCode, and the way back is what a reader of
    this database needs. Where EPA's spec carries no description the placeholder says so
    rather than inventing one -- a wrong description in database metadata is worse than a
    missing one.
*/

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @Description = N'Mirrors the RCRAInfo owners collection -- an array of objects with 30 leaf field(s) -- one row per element. Keyed to dbo.HandlerSource by surrogate key and ordered by OrdinalPosition.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'HandlerSourceOwnerId'
    , @Description = N'Surrogate key for one element of the RCRAInfo owners array.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'HandlerSourceId'
    , @Description = N'The dbo.HandlerSource version this row belongs to. Keyed to the surrogate key, never to HandlerId: keying a collection to HandlerId collapses every version of the handler into one list and corrupts the history.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'OrdinalPosition'
    , @Description = N'Zero-based position of this element within the RCRAInfo owners array. A JSON array is ordered, and EPA supplies no key for these elements, so the position is both the fidelity of the mirror and the only natural key this row has.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'Name'
    , @Description = N'The name of the entity (individual, agency, or corporation) having legal ownership of the physical operation. The owner name may or may not be the same as the actual site name or the operator name. [RCRAInfo: owners[].name]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'Phone'
    , @Description = N'Telephone number at which the site owner may be reached. Note: Phone numbers associated with US addresses may be formatted as 9999999999 or 999-999-9999 but will be stored in the database as 999-999-9999. [RCRAInfo: owners[].phone]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'PhoneExtension'
    , @Description = N'Telephone number extension associated with the site owner. [RCRAInfo: owners[].phoneExtension]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'Email'
    , @Description = N'Email address associated with the site owner. [RCRAInfo: owners[].email]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'Fax'
    , @Description = N'Facsimile number associated with the site owner or operator. Note: Fax numbers associated with US addresses may be formatted as 9999999999 or 999-999-9999 but will be stored in the database as 999-999-9999. [RCRAInfo: owners[].fax]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'BecameCurrent'
    , @Description = N'Date indicating when the owner became the current owner. [RCRAInfo: owners[].becameCurrent]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'EndedCurrent'
    , @Description = N'Date indicating when the owner changed to a different owner. Note: Beginning with V6, this data is no longer collected. [RCRAInfo: owners[].endedCurrent]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'AddressStreetNumber'
    , @Description = N'The street number from the address of the site owner. [RCRAInfo: owners[].address.streetNumber]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'AddressAddress1'
    , @Description = N'First line of the street address (or the post office box number) for the site owner. [RCRAInfo: owners[].address.address1]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'AddressAddress2'
    , @Description = N'Second line (as needed) of the street address for the site owner. [RCRAInfo: owners[].address.address2]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'AddressCity'
    , @Description = N'The city or town in the address of the site owner. [RCRAInfo: owners[].address.city]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'AddressStateActivityLocation'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: owners[].address.state.activityLocation]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'AddressStateCode'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: owners[].address.state.code]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'AddressStateDescription'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: owners[].address.state.description]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'AddressStateActive'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: owners[].address.state.active]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'AddressForeignStateActivityLocation'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: owners[].address.foreignState.activityLocation]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'AddressForeignStateCode'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: owners[].address.foreignState.code]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'AddressForeignStateDescription'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: owners[].address.foreignState.description]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'AddressForeignStateActive'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: owners[].address.foreignState.active]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'AddressForeignStateName'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: owners[].address.foreignState.name]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'AddressForeignStateCountryCode'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: owners[].address.foreignState.countryCode]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'AddressCountryActivityLocation'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: owners[].address.country.activityLocation]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'AddressCountryCode'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: owners[].address.country.code]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'AddressCountryDescription'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: owners[].address.country.description]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'AddressCountryActive'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: owners[].address.country.active]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'AddressZip'
    , @Description = N'Zip code in the address of the site owner. Note: Zip codes associated with US addresses may be formatted as 99999, 999999999, or 99999-9999 but will be stored in the database as 99999 or 99999-9999. [RCRAInfo: owners[].address.zip]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'SourceType'
    , @Description = N'Code for land type. [RCRAInfo: owners[].type.code]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'SourceTypeDescription'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: owners[].type.description]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'Notes'
    , @Description = N'Additional information regarding the owner. Note: These notes are not released to the public. [RCRAInfo: owners[].notes]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'PublicNotes'
    , @Description = N'Additional information regarding the owner. Note: These notes may be released to the public. [RCRAInfo: owners[].publicNotes]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'IsDeleted'
    , @Description = N'Soft-delete flag. 1 = deleted, 0 = active. This database performs no hard deletes; every read path filters IsDeleted = 0.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'auditDeletedBy'
    , @Description = N'Login that soft-deleted the row. Populated by DEFAULT on insert, so it is only meaningful when IsDeleted = 1.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'auditDeletedDateUtc'
    , @Description = N'UTC timestamp of the soft delete. Populated by DEFAULT on insert, so it is only meaningful when IsDeleted = 1; the deleting statement sets it explicitly.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'auditCreatedBy'
    , @Description = N'Login that inserted the row. Under the application logins this identifies which application wrote it, not an end user.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'auditCreatedDateUtc'
    , @Description = N'UTC timestamp of row insert. Set by DEFAULT; the loader omits this column from its INSERT column list so the default fires.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'auditModifiedBy'
    , @Description = N'Login that last modified the row.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceOwner'
    , @ColumnName  = N'auditModifiedDateUtc'
    , @Description = N'UTC timestamp of last modification. The DEFAULT fires on INSERT only, so every UPDATE and MERGE must set this column explicitly or the audit trail will claim the row has never changed.';
GO

PRINT N'131: dbo.HandlerSourceOwner created or altered, 40 column(s) described.';
GO
