/**********************************************************************************************************************
Script:       142_dbo.HandlerSourceEpisodicWaste.sql
Author:       generated by build/generate_schema.py
========================================================================================================================
Description:

Mirrors the RCRAInfo episodic.wastes collection -- an array of objects with 2 leaf field(s) -- one row per element.
Keyed to dbo.HandlerSource by surrogate key and ordered by OrdinalPosition.

GENERATED FILE -- do not edit by hand. Regenerate with:

    python build/generate_schema.py

Generated from one repeating collection in EPA's HandlerSource payload.

build/guardrails.py runs `generate_schema.py --check`, which fails if this file and the spec
have drifted apart, so editing it here is not merely discouraged -- it breaks the build.

========================================================================================================================
Notes:

RE-RUNNABLE. Every CREATE is guarded, descriptions go through util.uspSetObjectDescription
(which adds or updates), and nothing is dropped or truncated. A second run changes nothing.

Later changes are ADDITIVE: append a guarded ALTER TABLE ... ADD block rather than editing
the CREATE TABLE above, or the script stops converging on a database that already has the
table. In this file that means changing the generator, not the output.
**********************************************************************************************************************/

SET XACT_ABORT ON;
-- Not decoration: sqlcmd defaults QUOTED_IDENTIFIER OFF where every other client defaults it ON, the
-- setting is BAKED IN at CREATE time, and a module or session carrying it OFF cannot run DML against a
-- table with a filtered index (error 1934). Every unique constraint here is one. Set it so that a hand
-- run cannot get it wrong.
SET QUOTED_IDENTIFIER ON;
GO

----------------------------------------------------------------------------------------------------
-- 1. The table. Guarded, so a second run is a no-op.
----------------------------------------------------------------------------------------------------
IF OBJECT_ID (N'dbo.HandlerSourceEpisodicWaste', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.HandlerSourceEpisodicWaste
    (
        HandlerSourceEpisodicWasteId  INT              IDENTITY (1, 1) NOT NULL,
        HandlerSourceId               INT                              NOT NULL,
        OrdinalPosition               INT                              NOT NULL,
        Description                   NVARCHAR (4000)                      NULL,
        Quantity                      FLOAT                                NULL,
        IsDeleted                     BIT                              NOT NULL CONSTRAINT DF_dbo_HandlerSourceEpisodicWaste_IsDeleted DEFAULT (0),
        auditDeletedBy                NVARCHAR (128)                   NOT NULL CONSTRAINT DF_dbo_HandlerSourceEpisodicWaste_auditDeletedBy DEFAULT (ORIGINAL_LOGIN ()),
        auditDeletedDateUtc           DATETIME2                        NOT NULL CONSTRAINT DF_dbo_HandlerSourceEpisodicWaste_auditDeletedDateUtc DEFAULT (SYSUTCDATETIME ()),
        auditCreatedBy                NVARCHAR (128)                   NOT NULL CONSTRAINT DF_dbo_HandlerSourceEpisodicWaste_auditCreatedBy DEFAULT (ORIGINAL_LOGIN ()),
        auditCreatedDateUtc           DATETIME2                        NOT NULL CONSTRAINT DF_dbo_HandlerSourceEpisodicWaste_auditCreatedDateUtc DEFAULT (SYSUTCDATETIME ()),
        auditModifiedBy               NVARCHAR (128)                   NOT NULL CONSTRAINT DF_dbo_HandlerSourceEpisodicWaste_auditModifiedBy DEFAULT (ORIGINAL_LOGIN ()),
        auditModifiedDateUtc          DATETIME2                        NOT NULL CONSTRAINT DF_dbo_HandlerSourceEpisodicWaste_auditModifiedDateUtc DEFAULT (SYSUTCDATETIME ()),

        CONSTRAINT PK_dbo_HandlerSourceEpisodicWaste PRIMARY KEY CLUSTERED (HandlerSourceEpisodicWasteId)
    )
    WITH (DATA_COMPRESSION = PAGE);
END;
GO

----------------------------------------------------------------------------------------------------
-- 2. Natural key.
--    A filtered unique index, not a unique constraint: a soft-deleted row keeps its key,
--    and an unfiltered constraint would block re-creation of that key forever -- the load
--    would fail on a handler EPA had corrected and resubmitted.
----------------------------------------------------------------------------------------------------
IF NOT EXISTS (SELECT 1
                 FROM sys.indexes
                WHERE name      = N'UX_dbo_HandlerSourceEpisodicWaste_Natural'
                  AND object_id = OBJECT_ID (N'dbo.HandlerSourceEpisodicWaste'))
BEGIN
    CREATE UNIQUE INDEX UX_dbo_HandlerSourceEpisodicWaste_Natural
        ON dbo.HandlerSourceEpisodicWaste (HandlerSourceId, OrdinalPosition)
        WHERE IsDeleted = 0
        WITH (DATA_COMPRESSION = PAGE);
END;
GO

IF EXISTS (SELECT 1
             FROM sys.indexes AS i
             JOIN sys.partitions AS p
               ON p.object_id = i.object_id
              AND p.index_id  = i.index_id
            WHERE i.name      = N'UX_dbo_HandlerSourceEpisodicWaste_Natural'
              AND i.object_id = OBJECT_ID (N'dbo.HandlerSourceEpisodicWaste')
              AND p.data_compression_desc <> N'PAGE')
BEGIN
    ALTER INDEX UX_dbo_HandlerSourceEpisodicWaste_Natural
        ON dbo.HandlerSourceEpisodicWaste REBUILD WITH (DATA_COMPRESSION = PAGE);
END;
GO

----------------------------------------------------------------------------------------------------
-- 3. The foreign key column.
--    Deliberately NOT redundant with UX_dbo_HandlerSourceEpisodicWaste_Natural above. That index is filtered to
--    IsDeleted = 0, so it cannot serve a lookup that has to see soft-deleted rows -- and
--    for this loader that is a normal path, not an exceptional one. Nothing is ever hard-
--    deleted, so re-loading a handler means finding the existing child rows, including any
--    previously soft-deleted, and reviving them. Without this index that seek is a scan of
--    every child row in the table, for every handler in the batch.
----------------------------------------------------------------------------------------------------
IF NOT EXISTS (SELECT 1
                 FROM sys.indexes
                WHERE name      = N'IX_dbo_HandlerSourceEpisodicWaste_HandlerSourceId'
                  AND object_id = OBJECT_ID (N'dbo.HandlerSourceEpisodicWaste'))
BEGIN
    CREATE INDEX IX_dbo_HandlerSourceEpisodicWaste_HandlerSourceId
        ON dbo.HandlerSourceEpisodicWaste (HandlerSourceId)
        WITH (DATA_COMPRESSION = PAGE);
END;
GO

IF EXISTS (SELECT 1
             FROM sys.indexes AS i
             JOIN sys.partitions AS p
               ON p.object_id = i.object_id
              AND p.index_id  = i.index_id
            WHERE i.name      = N'IX_dbo_HandlerSourceEpisodicWaste_HandlerSourceId'
              AND i.object_id = OBJECT_ID (N'dbo.HandlerSourceEpisodicWaste')
              AND p.data_compression_desc <> N'PAGE')
BEGIN
    ALTER INDEX IX_dbo_HandlerSourceEpisodicWaste_HandlerSourceId
        ON dbo.HandlerSourceEpisodicWaste REBUILD WITH (DATA_COMPRESSION = PAGE);
END;
GO

----------------------------------------------------------------------------------------------------
-- Foreign key to the parent version. NO ACTION on delete, not CASCADE: this database
--    performs no hard deletes, so a cascade could never fire and declaring one would
--    advertise a behaviour that does not exist.
----------------------------------------------------------------------------------------------------
IF NOT EXISTS (SELECT 1
                 FROM sys.foreign_keys
                WHERE name = N'FK_dbo_HandlerSourceEpisodicWaste_HandlerSource')
BEGIN
    ALTER TABLE dbo.HandlerSourceEpisodicWaste
        ADD CONSTRAINT FK_dbo_HandlerSourceEpisodicWaste_HandlerSource FOREIGN KEY (HandlerSourceId)
            REFERENCES dbo.HandlerSource (HandlerSourceId);
END;
GO

/*
    Extended properties. Required on the table and on EVERY column.

    Through util.uspSetObjectDescription only. It adds or updates, so this script re-runs and
    an improved wording replaces the old one; a bare sp_addextendedproperty succeeds once and
    then fails on every subsequent run.

    Each column description ends with the RCRAInfo JSON path it mirrors. Flattening turned
    siteLocation.state.code into SiteLocationStateCode, and the way back is what a reader of
    this database needs. Where EPA's spec carries no description the placeholder says so
    rather than inventing one -- a wrong description in database metadata is worse than a
    missing one.
*/

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceEpisodicWaste'
    , @Description = N'Mirrors the RCRAInfo episodic.wastes collection -- an array of objects with 2 leaf field(s) -- one row per element. Keyed to dbo.HandlerSource by surrogate key and ordered by OrdinalPosition.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceEpisodicWaste'
    , @ColumnName  = N'HandlerSourceEpisodicWasteId'
    , @Description = N'Surrogate key for one element of the RCRAInfo episodic.wastes array.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceEpisodicWaste'
    , @ColumnName  = N'HandlerSourceId'
    , @Description = N'The dbo.HandlerSource version this row belongs to. Keyed to the surrogate key, never to HandlerId: keying a collection to HandlerId collapses every version of the handler into one list and corrupts the history.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceEpisodicWaste'
    , @ColumnName  = N'OrdinalPosition'
    , @Description = N'Zero-based position of this element within the RCRAInfo episodic.wastes array. A JSON array is ordered, and EPA supplies no key for these elements, so the position is both the fidelity of the mirror and the only natural key this row has.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceEpisodicWaste'
    , @ColumnName  = N'Description'
    , @Description = N'A description of the waste generated as a result of the episodic event. [RCRAInfo: episodic.wastes[].description]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceEpisodicWaste'
    , @ColumnName  = N'Quantity'
    , @Description = N'Estimated Quantity (in pounds) [RCRAInfo: episodic.wastes[].quantity]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceEpisodicWaste'
    , @ColumnName  = N'IsDeleted'
    , @Description = N'Soft-delete flag. 1 = deleted, 0 = active. This database performs no hard deletes; every read path filters IsDeleted = 0.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceEpisodicWaste'
    , @ColumnName  = N'auditDeletedBy'
    , @Description = N'Login that soft-deleted the row. Populated by DEFAULT on insert, so it is only meaningful when IsDeleted = 1.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceEpisodicWaste'
    , @ColumnName  = N'auditDeletedDateUtc'
    , @Description = N'UTC timestamp of the soft delete. Populated by DEFAULT on insert, so it is only meaningful when IsDeleted = 1; the deleting statement sets it explicitly.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceEpisodicWaste'
    , @ColumnName  = N'auditCreatedBy'
    , @Description = N'Login that inserted the row. Under the application logins this identifies which application wrote it, not an end user.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceEpisodicWaste'
    , @ColumnName  = N'auditCreatedDateUtc'
    , @Description = N'UTC timestamp of row insert. Set by DEFAULT; the loader omits this column from its INSERT column list so the default fires.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceEpisodicWaste'
    , @ColumnName  = N'auditModifiedBy'
    , @Description = N'Login that last modified the row.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceEpisodicWaste'
    , @ColumnName  = N'auditModifiedDateUtc'
    , @Description = N'UTC timestamp of last modification. The DEFAULT fires on INSERT only, so every UPDATE and MERGE must set this column explicitly or the audit trail will claim the row has never changed.';
GO

PRINT N'142: dbo.HandlerSourceEpisodicWaste created or altered, 12 column(s) described.';
GO
