/**********************************************************************************************************************
Script:       147_dbo.HandlerSourceLqgConsolidationVsqg.sql
Author:       generated by build/generate_schema.py
========================================================================================================================
Description:

Mirrors the RCRAInfo lqgConsolidationsVsqgs collection -- an array of objects with 17 leaf field(s) -- one row per
element. Keyed to dbo.HandlerSource by surrogate key and ordered by OrdinalPosition.

GENERATED FILE -- do not edit by hand. Regenerate with:

    python build/generate_schema.py

Generated from one repeating collection in EPA's HandlerSource payload.

build/guardrails.py runs `generate_schema.py --check`, which fails if this file and the spec
have drifted apart, so editing it here is not merely discouraged -- it breaks the build.

========================================================================================================================
Notes:

RE-RUNNABLE. Every CREATE is guarded, descriptions go through util.uspSetObjectDescription
(which adds or updates), and nothing is dropped or truncated. A second run changes nothing.

Later changes are ADDITIVE: append a guarded ALTER TABLE ... ADD block rather than editing
the CREATE TABLE above, or the script stops converging on a database that already has the
table. In this file that means changing the generator, not the output.
**********************************************************************************************************************/

SET XACT_ABORT ON;
-- Not decoration: sqlcmd defaults QUOTED_IDENTIFIER OFF where every other client defaults it ON, the
-- setting is BAKED IN at CREATE time, and a module or session carrying it OFF cannot run DML against a
-- table with a filtered index (error 1934). Every unique constraint here is one. Set it so that a hand
-- run cannot get it wrong.
SET QUOTED_IDENTIFIER ON;
GO

----------------------------------------------------------------------------------------------------
-- 1. The table. Guarded, so a second run is a no-op.
----------------------------------------------------------------------------------------------------
IF OBJECT_ID (N'dbo.HandlerSourceLqgConsolidationVsqg', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.HandlerSourceLqgConsolidationVsqg
    (
        HandlerSourceLqgConsolidationVsqgId  INT             IDENTITY (1, 1) NOT NULL,
        HandlerSourceId                      INT                             NOT NULL,
        OrdinalPosition                      INT                             NOT NULL,
        HandlerId                            NVARCHAR (12)                       NULL,
        HandlerName                          NVARCHAR (80)                       NULL,
        StreetNumber                         NVARCHAR (12)                       NULL,
        Address1                             NVARCHAR (50)                       NULL,
        Address2                             NVARCHAR (50)                       NULL,
        City                                 NVARCHAR (25)                       NULL,
        StateActivityLocation                NVARCHAR (2)                        NULL,
        StateCode                            NVARCHAR (2)                        NULL,
        StateDescription                     NVARCHAR (255)                      NULL,
        StateActive                          BIT                                 NULL,
        Zip                                  NVARCHAR (14)                       NULL,
        FirstName                            NVARCHAR (38)                       NULL,
        MiddleInitial                        NVARCHAR (1)                        NULL,
        LastName                             NVARCHAR (38)                       NULL,
        Email                                NVARCHAR (80)                       NULL,
        Phone                                NVARCHAR (15)                       NULL,
        PhoneExtension                       NVARCHAR (6)                        NULL,
        IsDeleted                            BIT                             NOT NULL CONSTRAINT DF_dbo_HandlerSourceLqgConsolidationVsqg_IsDeleted DEFAULT (0),
        auditDeletedBy                       NVARCHAR (128)                  NOT NULL CONSTRAINT DF_dbo_HandlerSourceLqgConsolidationVsqg_auditDeletedBy DEFAULT (ORIGINAL_LOGIN ()),
        auditDeletedDateUtc                  DATETIME2                       NOT NULL CONSTRAINT DF_dbo_HandlerSourceLqgConsolidationVsqg_auditDeletedDateUtc DEFAULT (SYSUTCDATETIME ()),
        auditCreatedBy                       NVARCHAR (128)                  NOT NULL CONSTRAINT DF_dbo_HandlerSourceLqgConsolidationVsqg_auditCreatedBy DEFAULT (ORIGINAL_LOGIN ()),
        auditCreatedDateUtc                  DATETIME2                       NOT NULL CONSTRAINT DF_dbo_HandlerSourceLqgConsolidationVsqg_auditCreatedDateUtc DEFAULT (SYSUTCDATETIME ()),
        auditModifiedBy                      NVARCHAR (128)                  NOT NULL CONSTRAINT DF_dbo_HandlerSourceLqgConsolidationVsqg_auditModifiedBy DEFAULT (ORIGINAL_LOGIN ()),
        auditModifiedDateUtc                 DATETIME2                       NOT NULL CONSTRAINT DF_dbo_HandlerSourceLqgConsolidationVsqg_auditModifiedDateUtc DEFAULT (SYSUTCDATETIME ()),

        CONSTRAINT PK_dbo_HandlerSourceLqgConsolidationVsqg PRIMARY KEY CLUSTERED (HandlerSourceLqgConsolidationVsqgId)
    )
    WITH (DATA_COMPRESSION = PAGE);
END;
GO

----------------------------------------------------------------------------------------------------
-- 2. Natural key.
--    A filtered unique index, not a unique constraint: a soft-deleted row keeps its key,
--    and an unfiltered constraint would block re-creation of that key forever -- the load
--    would fail on a handler EPA had corrected and resubmitted.
----------------------------------------------------------------------------------------------------
IF NOT EXISTS (SELECT 1
                 FROM sys.indexes
                WHERE name      = N'UX_dbo_HandlerSourceLqgConsolidationVsqg_Natural'
                  AND object_id = OBJECT_ID (N'dbo.HandlerSourceLqgConsolidationVsqg'))
BEGIN
    CREATE UNIQUE INDEX UX_dbo_HandlerSourceLqgConsolidationVsqg_Natural
        ON dbo.HandlerSourceLqgConsolidationVsqg (HandlerSourceId, OrdinalPosition)
        WHERE IsDeleted = 0
        WITH (DATA_COMPRESSION = PAGE);
END;
GO

IF EXISTS (SELECT 1
             FROM sys.indexes AS i
             JOIN sys.partitions AS p
               ON p.object_id = i.object_id
              AND p.index_id  = i.index_id
            WHERE i.name      = N'UX_dbo_HandlerSourceLqgConsolidationVsqg_Natural'
              AND i.object_id = OBJECT_ID (N'dbo.HandlerSourceLqgConsolidationVsqg')
              AND p.data_compression_desc <> N'PAGE')
BEGIN
    ALTER INDEX UX_dbo_HandlerSourceLqgConsolidationVsqg_Natural
        ON dbo.HandlerSourceLqgConsolidationVsqg REBUILD WITH (DATA_COMPRESSION = PAGE);
END;
GO

----------------------------------------------------------------------------------------------------
-- 3. The foreign key column.
--    Deliberately NOT redundant with UX_dbo_HandlerSourceLqgConsolidationVsqg_Natural above. That index is filtered to
--    IsDeleted = 0, so it cannot serve a lookup that has to see soft-deleted rows -- and
--    for this loader that is a normal path, not an exceptional one. Nothing is ever hard-
--    deleted, so re-loading a handler means finding the existing child rows, including any
--    previously soft-deleted, and reviving them. Without this index that seek is a scan of
--    every child row in the table, for every handler in the batch.
----------------------------------------------------------------------------------------------------
IF NOT EXISTS (SELECT 1
                 FROM sys.indexes
                WHERE name      = N'IX_dbo_HandlerSourceLqgConsolidationVsqg_HandlerSourceId'
                  AND object_id = OBJECT_ID (N'dbo.HandlerSourceLqgConsolidationVsqg'))
BEGIN
    CREATE INDEX IX_dbo_HandlerSourceLqgConsolidationVsqg_HandlerSourceId
        ON dbo.HandlerSourceLqgConsolidationVsqg (HandlerSourceId)
        WITH (DATA_COMPRESSION = PAGE);
END;
GO

IF EXISTS (SELECT 1
             FROM sys.indexes AS i
             JOIN sys.partitions AS p
               ON p.object_id = i.object_id
              AND p.index_id  = i.index_id
            WHERE i.name      = N'IX_dbo_HandlerSourceLqgConsolidationVsqg_HandlerSourceId'
              AND i.object_id = OBJECT_ID (N'dbo.HandlerSourceLqgConsolidationVsqg')
              AND p.data_compression_desc <> N'PAGE')
BEGIN
    ALTER INDEX IX_dbo_HandlerSourceLqgConsolidationVsqg_HandlerSourceId
        ON dbo.HandlerSourceLqgConsolidationVsqg REBUILD WITH (DATA_COMPRESSION = PAGE);
END;
GO

----------------------------------------------------------------------------------------------------
-- Foreign key to the parent version. NO ACTION on delete, not CASCADE: this database
--    performs no hard deletes, so a cascade could never fire and declaring one would
--    advertise a behaviour that does not exist.
----------------------------------------------------------------------------------------------------
IF NOT EXISTS (SELECT 1
                 FROM sys.foreign_keys
                WHERE name = N'FK_dbo_HandlerSourceLqgConsolidationVsqg_HandlerSource')
BEGIN
    ALTER TABLE dbo.HandlerSourceLqgConsolidationVsqg
        ADD CONSTRAINT FK_dbo_HandlerSourceLqgConsolidationVsqg_HandlerSource FOREIGN KEY (HandlerSourceId)
            REFERENCES dbo.HandlerSource (HandlerSourceId);
END;
GO

/*
    Extended properties. Required on the table and on EVERY column.

    Through util.uspSetObjectDescription only. It adds or updates, so this script re-runs and
    an improved wording replaces the old one; a bare sp_addextendedproperty succeeds once and
    then fails on every subsequent run.

    Each column description ends with the RCRAInfo JSON path it mirrors. Flattening turned
    siteLocation.state.code into SiteLocationStateCode, and the way back is what a reader of
    this database needs. Where EPA's spec carries no description the placeholder says so
    rather than inventing one -- a wrong description in database metadata is worse than a
    missing one.
*/

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceLqgConsolidationVsqg'
    , @Description = N'Mirrors the RCRAInfo lqgConsolidationsVsqgs collection -- an array of objects with 17 leaf field(s) -- one row per element. Keyed to dbo.HandlerSource by surrogate key and ordered by OrdinalPosition.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceLqgConsolidationVsqg'
    , @ColumnName  = N'HandlerSourceLqgConsolidationVsqgId'
    , @Description = N'Surrogate key for one element of the RCRAInfo lqgConsolidationsVsqgs array.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceLqgConsolidationVsqg'
    , @ColumnName  = N'HandlerSourceId'
    , @Description = N'The dbo.HandlerSource version this row belongs to. Keyed to the surrogate key, never to HandlerId: keying a collection to HandlerId collapses every version of the handler into one list and corrupts the history.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceLqgConsolidationVsqg'
    , @ColumnName  = N'OrdinalPosition'
    , @Description = N'Zero-based position of this element within the RCRAInfo lqgConsolidationsVsqgs array. A JSON array is ordered, and EPA supplies no key for these elements, so the position is both the fidelity of the mirror and the only natural key this row has.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceLqgConsolidationVsqg'
    , @ColumnName  = N'HandlerId'
    , @Description = N'The EPA Identification Number for the VSQG whose waste is being consolidated. [RCRAInfo: lqgConsolidationsVsqgs[].handlerId]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceLqgConsolidationVsqg'
    , @ColumnName  = N'HandlerName'
    , @Description = N'The legal name of the VSQG. [RCRAInfo: lqgConsolidationsVsqgs[].handlerName]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceLqgConsolidationVsqg'
    , @ColumnName  = N'StreetNumber'
    , @Description = N'The street number from the site (physical) address of the VSQG. [RCRAInfo: lqgConsolidationsVsqgs[].streetNumber]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceLqgConsolidationVsqg'
    , @ColumnName  = N'Address1'
    , @Description = N'First line of the site (physical) street address for the VSQG. [RCRAInfo: lqgConsolidationsVsqgs[].address1]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceLqgConsolidationVsqg'
    , @ColumnName  = N'Address2'
    , @Description = N'Second line (as needed) of the site (physical) street address for the VSQG. [RCRAInfo: lqgConsolidationsVsqgs[].address2]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceLqgConsolidationVsqg'
    , @ColumnName  = N'City'
    , @Description = N'The city or town in the site (physical) address of the VSQG. [RCRAInfo: lqgConsolidationsVsqgs[].city]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceLqgConsolidationVsqg'
    , @ColumnName  = N'StateActivityLocation'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: lqgConsolidationsVsqgs[].state.activityLocation]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceLqgConsolidationVsqg'
    , @ColumnName  = N'StateCode'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: lqgConsolidationsVsqgs[].state.code]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceLqgConsolidationVsqg'
    , @ColumnName  = N'StateDescription'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: lqgConsolidationsVsqgs[].state.description]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceLqgConsolidationVsqg'
    , @ColumnName  = N'StateActive'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: lqgConsolidationsVsqgs[].state.active]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceLqgConsolidationVsqg'
    , @ColumnName  = N'Zip'
    , @Description = N'Zip code in the site (physical) address of the VSQG. Note: Zip codes associated with US addresses may be formatted as 99999, 999999999, or 99999-9999 but will be stored in the database as 99999 or 99999-9999. [RCRAInfo: lqgConsolidationsVsqgs[].zip]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceLqgConsolidationVsqg'
    , @ColumnName  = N'FirstName'
    , @Description = N'First name of the individual who should be contacted for information about the VSQG. [RCRAInfo: lqgConsolidationsVsqgs[].firstName]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceLqgConsolidationVsqg'
    , @ColumnName  = N'MiddleInitial'
    , @Description = N'Middle initial of the individual who should be contacted for information about the VSQG. [RCRAInfo: lqgConsolidationsVsqgs[].middleInitial]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceLqgConsolidationVsqg'
    , @ColumnName  = N'LastName'
    , @Description = N'Last name of the individual who should be contacted for information about the VSQG. [RCRAInfo: lqgConsolidationsVsqgs[].lastName]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceLqgConsolidationVsqg'
    , @ColumnName  = N'Email'
    , @Description = N'Email address of the VSQG contact. [RCRAInfo: lqgConsolidationsVsqgs[].email]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceLqgConsolidationVsqg'
    , @ColumnName  = N'Phone'
    , @Description = N'Telephone number at which the VSQG contact may be reached. Note: Phone numbers associated with US addresses may be formatted as 9999999999 or 999-999-9999 but will be stored in the database as 999-999-9999. [RCRAInfo: lqgConsolidationsVsqgs[].phone]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceLqgConsolidationVsqg'
    , @ColumnName  = N'PhoneExtension'
    , @Description = N'Telephone number extension associated with the VSQG contact. [RCRAInfo: lqgConsolidationsVsqgs[].phoneExtension]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceLqgConsolidationVsqg'
    , @ColumnName  = N'IsDeleted'
    , @Description = N'Soft-delete flag. 1 = deleted, 0 = active. This database performs no hard deletes; every read path filters IsDeleted = 0.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceLqgConsolidationVsqg'
    , @ColumnName  = N'auditDeletedBy'
    , @Description = N'Login that soft-deleted the row. Populated by DEFAULT on insert, so it is only meaningful when IsDeleted = 1.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceLqgConsolidationVsqg'
    , @ColumnName  = N'auditDeletedDateUtc'
    , @Description = N'UTC timestamp of the soft delete. Populated by DEFAULT on insert, so it is only meaningful when IsDeleted = 1; the deleting statement sets it explicitly.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceLqgConsolidationVsqg'
    , @ColumnName  = N'auditCreatedBy'
    , @Description = N'Login that inserted the row. Under the application logins this identifies which application wrote it, not an end user.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceLqgConsolidationVsqg'
    , @ColumnName  = N'auditCreatedDateUtc'
    , @Description = N'UTC timestamp of row insert. Set by DEFAULT; the loader omits this column from its INSERT column list so the default fires.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceLqgConsolidationVsqg'
    , @ColumnName  = N'auditModifiedBy'
    , @Description = N'Login that last modified the row.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerSourceLqgConsolidationVsqg'
    , @ColumnName  = N'auditModifiedDateUtc'
    , @Description = N'UTC timestamp of last modification. The DEFAULT fires on INSERT only, so every UPDATE and MERGE must set this column explicitly or the audit trail will claim the row has never changed.';
GO

PRINT N'147: dbo.HandlerSourceLqgConsolidationVsqg created or altered, 27 column(s) described.';
GO
