/**********************************************************************************************************************
Script:       150_dbo.HandlerOtherIdentifier.sql
Author:       generated by build/generate_schema.py
========================================================================================================================
Description:

Identifiers assigned to a handler outside RCRAInfo, mirrored from EPA's HandlerOtherId shape as returned by
/api/v1/hd/other-ids. In scope per G14, at the cost of one extra API call per handler. THIS IS THE ONE MIRRORED TABLE
IN THIS DATABASE THAT IS NOT VERSION-GRAINED, and the exception is EPA's, not a convenience: their endpoint is keyed
by handlerId alone, neither the request nor the response carries a sequence, so an other-id belongs to the handler
rather than to one submitted version of it. It therefore keys to (HandlerId, ActivityLocation, OtherId) and takes NO
foreign key to dbo.HandlerSource -- HandlerId is deliberately not unique there, and a foreign key to the surrogate key
would assert a grain the data does not have. Read it by HandlerId and join it to whichever version you are reporting
on; the association is to the handler. The table is named HandlerOtherIdentifier rather than HandlerOtherId so that
its surrogate key reads HandlerOtherIdentifierId and not HandlerOtherIdId.

GENERATED FILE -- do not edit by hand. Regenerate with:

    python build/generate_schema.py

Generated from EPA's HandlerOtherId definition -- the response shape of /api/v1/hd/other-ids, a separate endpoint
rather than a subtree of HandlerSource, and the only table here not keyed to a HandlerSource version. SameFacility
carries no CHECK constraint even though EPA declares the pattern Y|N|U: nothing in this mirror constrains a value EPA
may extend, because a rejected value fails an unattended overnight load instead of being reported.

build/guardrails.py runs `generate_schema.py --check`, which fails if this file and the spec
have drifted apart, so editing it here is not merely discouraged -- it breaks the build.

========================================================================================================================
Notes:

RE-RUNNABLE. Every CREATE is guarded, descriptions go through util.uspSetObjectDescription
(which adds or updates), and nothing is dropped or truncated. A second run changes nothing.

Later changes are ADDITIVE: append a guarded ALTER TABLE ... ADD block rather than editing
the CREATE TABLE above, or the script stops converging on a database that already has the
table. In this file that means changing the generator, not the output.
**********************************************************************************************************************/

SET XACT_ABORT ON;
-- Not decoration: sqlcmd defaults QUOTED_IDENTIFIER OFF where every other client defaults it ON, the
-- setting is BAKED IN at CREATE time, and a module or session carrying it OFF cannot run DML against a
-- table with a filtered index (error 1934). Every unique constraint here is one. Set it so that a hand
-- run cannot get it wrong.
SET QUOTED_IDENTIFIER ON;
GO

----------------------------------------------------------------------------------------------------
-- 1. The table. Guarded, so a second run is a no-op.
----------------------------------------------------------------------------------------------------
IF OBJECT_ID (N'dbo.HandlerOtherIdentifier', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.HandlerOtherIdentifier
    (
        HandlerOtherIdentifierId      INT              IDENTITY (1, 1) NOT NULL,
        HandlerId                     NVARCHAR (12)                    NOT NULL,
        ActivityLocation              NVARCHAR (2)                     NOT NULL,
        OtherId                       NVARCHAR (12)                    NOT NULL,
        RelationshipActivityLocation  NVARCHAR (2)                         NULL,
        RelationshipCode              NVARCHAR (1)                         NULL,
        RelationshipDescription       NVARCHAR (255)                       NULL,
        RelationshipActive            BIT                                  NULL,
        SameFacility                  NVARCHAR (1)                         NULL,
        HandlerLink                   BIT                                  NULL,
        Notes                         NVARCHAR (4000)                      NULL,
        PublicNotes                   NVARCHAR (4000)                      NULL,
        SrcUpdatedDate                DATE                                 NULL,
        SrcUpdatedBy                  NVARCHAR (100)                       NULL,
        IsDeleted                     BIT                              NOT NULL CONSTRAINT DF_dbo_HandlerOtherIdentifier_IsDeleted DEFAULT (0),
        auditDeletedBy                NVARCHAR (128)                   NOT NULL CONSTRAINT DF_dbo_HandlerOtherIdentifier_auditDeletedBy DEFAULT (ORIGINAL_LOGIN ()),
        auditDeletedDateUtc           DATETIME2                        NOT NULL CONSTRAINT DF_dbo_HandlerOtherIdentifier_auditDeletedDateUtc DEFAULT (SYSUTCDATETIME ()),
        auditCreatedBy                NVARCHAR (128)                   NOT NULL CONSTRAINT DF_dbo_HandlerOtherIdentifier_auditCreatedBy DEFAULT (ORIGINAL_LOGIN ()),
        auditCreatedDateUtc           DATETIME2                        NOT NULL CONSTRAINT DF_dbo_HandlerOtherIdentifier_auditCreatedDateUtc DEFAULT (SYSUTCDATETIME ()),
        auditModifiedBy               NVARCHAR (128)                   NOT NULL CONSTRAINT DF_dbo_HandlerOtherIdentifier_auditModifiedBy DEFAULT (ORIGINAL_LOGIN ()),
        auditModifiedDateUtc          DATETIME2                        NOT NULL CONSTRAINT DF_dbo_HandlerOtherIdentifier_auditModifiedDateUtc DEFAULT (SYSUTCDATETIME ()),

        CONSTRAINT PK_dbo_HandlerOtherIdentifier PRIMARY KEY CLUSTERED (HandlerOtherIdentifierId)
    )
    WITH (DATA_COMPRESSION = PAGE);
END;
GO

----------------------------------------------------------------------------------------------------
-- 2. Natural key.
--    A filtered unique index, not a unique constraint: a soft-deleted row keeps its key,
--    and an unfiltered constraint would block re-creation of that key forever -- the load
--    would fail on a handler EPA had corrected and resubmitted.
----------------------------------------------------------------------------------------------------
IF NOT EXISTS (SELECT 1
                 FROM sys.indexes
                WHERE name      = N'UX_dbo_HandlerOtherIdentifier_Natural'
                  AND object_id = OBJECT_ID (N'dbo.HandlerOtherIdentifier'))
BEGIN
    CREATE UNIQUE INDEX UX_dbo_HandlerOtherIdentifier_Natural
        ON dbo.HandlerOtherIdentifier (HandlerId, ActivityLocation, OtherId)
        WHERE IsDeleted = 0
        WITH (DATA_COMPRESSION = PAGE);
END;
GO

IF EXISTS (SELECT 1
             FROM sys.indexes AS i
             JOIN sys.partitions AS p
               ON p.object_id = i.object_id
              AND p.index_id  = i.index_id
            WHERE i.name      = N'UX_dbo_HandlerOtherIdentifier_Natural'
              AND i.object_id = OBJECT_ID (N'dbo.HandlerOtherIdentifier')
              AND p.data_compression_desc <> N'PAGE')
BEGIN
    ALTER INDEX UX_dbo_HandlerOtherIdentifier_Natural
        ON dbo.HandlerOtherIdentifier REBUILD WITH (DATA_COMPRESSION = PAGE);
END;
GO

----------------------------------------------------------------------------------------------------
-- Supporting index.
--    EPA's natural key again, unfiltered. UX_dbo_HandlerOtherIdentifier_Natural excludes
--    soft-deleted rows, so it cannot serve the loader's lookup of a row it may need to revive
--    rather than duplicate. Leading with HandlerId, it also serves the obvious read: every other-id
--    recorded for one handler.
----------------------------------------------------------------------------------------------------
IF NOT EXISTS (SELECT 1
                 FROM sys.indexes
                WHERE name      = N'IX_dbo_HandlerOtherIdentifier_HandlerAll'
                  AND object_id = OBJECT_ID (N'dbo.HandlerOtherIdentifier'))
BEGIN
    CREATE INDEX IX_dbo_HandlerOtherIdentifier_HandlerAll
        ON dbo.HandlerOtherIdentifier (HandlerId, ActivityLocation, OtherId)
        WITH (DATA_COMPRESSION = PAGE);
END;
GO

IF EXISTS (SELECT 1
             FROM sys.indexes AS i
             JOIN sys.partitions AS p
               ON p.object_id = i.object_id
              AND p.index_id  = i.index_id
            WHERE i.name      = N'IX_dbo_HandlerOtherIdentifier_HandlerAll'
              AND i.object_id = OBJECT_ID (N'dbo.HandlerOtherIdentifier')
              AND p.data_compression_desc <> N'PAGE')
BEGIN
    ALTER INDEX IX_dbo_HandlerOtherIdentifier_HandlerAll
        ON dbo.HandlerOtherIdentifier REBUILD WITH (DATA_COMPRESSION = PAGE);
END;
GO

/*
    Extended properties. Required on the table and on EVERY column.

    Through util.uspSetObjectDescription only. It adds or updates, so this script re-runs and
    an improved wording replaces the old one; a bare sp_addextendedproperty succeeds once and
    then fails on every subsequent run.

    Each column description ends with the RCRAInfo JSON path it mirrors. Flattening turned
    siteLocation.state.code into SiteLocationStateCode, and the way back is what a reader of
    this database needs. Where EPA's spec carries no description the placeholder says so
    rather than inventing one -- a wrong description in database metadata is worse than a
    missing one.
*/

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerOtherIdentifier'
    , @Description = N'Identifiers assigned to a handler outside RCRAInfo, mirrored from EPA''s HandlerOtherId shape as returned by /api/v1/hd/other-ids. In scope per G14, at the cost of one extra API call per handler. THIS IS THE ONE MIRRORED TABLE IN THIS DATABASE THAT IS NOT VERSION-GRAINED, and the exception is EPA''s, not a convenience: their endpoint is keyed by handlerId alone, neither the request nor the response carries a sequence, so an other-id belongs to the handler rather than to one submitted version of it. It therefore keys to (HandlerId, ActivityLocation, OtherId) and takes NO foreign key to dbo.HandlerSource -- HandlerId is deliberately not unique there, and a foreign key to the surrogate key would assert a grain the data does not have. Read it by HandlerId and join it to whichever version you are reporting on; the association is to the handler. The table is named HandlerOtherIdentifier rather than HandlerOtherId so that its surrogate key reads HandlerOtherIdentifierId and not HandlerOtherIdId.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerOtherIdentifier'
    , @ColumnName  = N'HandlerOtherIdentifierId'
    , @Description = N'Surrogate key. EPA''s own identity for one of these rows is (HandlerId, ActivityLocation, OtherId) -- the three values their DELETE path takes -- enforced here by a filtered unique index.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerOtherIdentifier'
    , @ColumnName  = N'HandlerId'
    , @Description = N'Existing Handler Id which should be assigned another id. [RCRAInfo: other-ids[].handlerId]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerOtherIdentifier'
    , @ColumnName  = N'ActivityLocation'
    , @Description = N'The location (i.e. State) where the activity took place. This activity location may be in another location from where original handler id was assigned. [RCRAInfo: other-ids[].activityLocation]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerOtherIdentifier'
    , @ColumnName  = N'OtherId'
    , @Description = N'Another identifier that has been assigned to an existing handler id. This maybe another valid handler id or any other value assigned by an external system. [RCRAInfo: other-ids[].otherId]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerOtherIdentifier'
    , @ColumnName  = N'RelationshipActivityLocation'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: other-ids[].relationship.activityLocation]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerOtherIdentifier'
    , @ColumnName  = N'RelationshipCode'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: other-ids[].relationship.code]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerOtherIdentifier'
    , @ColumnName  = N'RelationshipDescription'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: other-ids[].relationship.description]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerOtherIdentifier'
    , @ColumnName  = N'RelationshipActive'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: other-ids[].relationship.active]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerOtherIdentifier'
    , @ColumnName  = N'SameFacility'
    , @Description = N'Possible values are Y, N or U. Y indicates that the other id is for the same facility as the handler id. N indicates that the other id is for a different facility. U indicates that the relationship is unknown. [RCRAInfo: other-ids[].sameFacility]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerOtherIdentifier'
    , @ColumnName  = N'HandlerLink'
    , @Description = N'Indicates if the other id is linked to a handler in RCRAInfo. [RCRAInfo: other-ids[].handlerLink]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerOtherIdentifier'
    , @ColumnName  = N'Notes'
    , @Description = N'Notes about the other id. [RCRAInfo: other-ids[].notes]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerOtherIdentifier'
    , @ColumnName  = N'PublicNotes'
    , @Description = N'Public notes about the other id. [RCRAInfo: other-ids[].publicNotes]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerOtherIdentifier'
    , @ColumnName  = N'SrcUpdatedDate'
    , @Description = N'Date when this other id was last updated updated. [RCRAInfo: other-ids[].updatedDate]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerOtherIdentifier'
    , @ColumnName  = N'SrcUpdatedBy'
    , @Description = N'User that last modified this record. [RCRAInfo: other-ids[].updatedBy]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerOtherIdentifier'
    , @ColumnName  = N'IsDeleted'
    , @Description = N'Soft-delete flag. 1 = deleted, 0 = active. This database performs no hard deletes; every read path filters IsDeleted = 0.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerOtherIdentifier'
    , @ColumnName  = N'auditDeletedBy'
    , @Description = N'Login that soft-deleted the row. Populated by DEFAULT on insert, so it is only meaningful when IsDeleted = 1.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerOtherIdentifier'
    , @ColumnName  = N'auditDeletedDateUtc'
    , @Description = N'UTC timestamp of the soft delete. Populated by DEFAULT on insert, so it is only meaningful when IsDeleted = 1; the deleting statement sets it explicitly.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerOtherIdentifier'
    , @ColumnName  = N'auditCreatedBy'
    , @Description = N'Login that inserted the row. Under the application logins this identifies which application wrote it, not an end user.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerOtherIdentifier'
    , @ColumnName  = N'auditCreatedDateUtc'
    , @Description = N'UTC timestamp of row insert. Set by DEFAULT; the loader omits this column from its INSERT column list so the default fires.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerOtherIdentifier'
    , @ColumnName  = N'auditModifiedBy'
    , @Description = N'Login that last modified the row.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'HandlerOtherIdentifier'
    , @ColumnName  = N'auditModifiedDateUtc'
    , @Description = N'UTC timestamp of last modification. The DEFAULT fires on INSERT only, so every UPDATE and MERGE must set this column explicitly or the audit trail will claim the row has never changed.';
GO

PRINT N'150: dbo.HandlerOtherIdentifier created or altered, 21 column(s) described.';
GO
