/**********************************************************************************************************************
Script:       206_dbo.LookupGeneratorCategory.sql
Author:       generated by build/generate_schema.py
========================================================================================================================
Description:

Mirror of the EPA RCRAInfo GeneratorCategory code list, served by /lookup/hd/generator-categories. Retired codes are
SOFT-DELETED and must still resolve: a code EPA retires this year is still the correct code for a handler version
submitted while it was current, so a historical read must NOT filter IsDeleted = 0 on this table. That is the one
documented exception to this database's blanket read rule. No handler table takes a foreign key to this one (see
Phase1-Plan.md B2): the lists load independently, and a code that arrives on a handler before it appears in the
mirrored list is a data-quality observation, not a failed load.

GENERATED FILE -- do not edit by hand. Regenerate with:

    python build/generate_schema.py

Generated from one lookup/hd response definition. Mirrored per G15. (Written without the glob character on purpose: a
T-SQL block comment nests, so a slash-star inside this header would swallow its own terminator.)

build/guardrails.py runs `generate_schema.py --check`, which fails if this file and the spec
have drifted apart, so editing it here is not merely discouraged -- it breaks the build.

========================================================================================================================
Notes:

RE-RUNNABLE. Every CREATE is guarded, descriptions go through util.uspSetObjectDescription
(which adds or updates), and nothing is dropped or truncated. A second run changes nothing.

Later changes are ADDITIVE: append a guarded ALTER TABLE ... ADD block rather than editing
the CREATE TABLE above, or the script stops converging on a database that already has the
table. In this file that means changing the generator, not the output.
**********************************************************************************************************************/

SET XACT_ABORT ON;
-- Not decoration: sqlcmd defaults QUOTED_IDENTIFIER OFF where every other client defaults it ON, the
-- setting is BAKED IN at CREATE time, and a module or session carrying it OFF cannot run DML against a
-- table with a filtered index (error 1934). Every unique constraint here is one. Set it so that a hand
-- run cannot get it wrong.
SET QUOTED_IDENTIFIER ON;
GO

----------------------------------------------------------------------------------------------------
-- 1. The table. Guarded, so a second run is a no-op.
----------------------------------------------------------------------------------------------------
IF OBJECT_ID (N'dbo.LookupGeneratorCategory', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.LookupGeneratorCategory
    (
        LookupGeneratorCategoryId  INT             IDENTITY (1, 1) NOT NULL,
        ActivityLocation           NVARCHAR (2)                    NOT NULL,
        Code                       NVARCHAR (1)                    NOT NULL,
        Description                NVARCHAR (255)                      NULL,
        Active                     BIT                                 NULL,
        IsDeleted                  BIT                             NOT NULL CONSTRAINT DF_dbo_LookupGeneratorCategory_IsDeleted DEFAULT (0),
        auditDeletedBy             NVARCHAR (128)                  NOT NULL CONSTRAINT DF_dbo_LookupGeneratorCategory_auditDeletedBy DEFAULT (ORIGINAL_LOGIN ()),
        auditDeletedDateUtc        DATETIME2                       NOT NULL CONSTRAINT DF_dbo_LookupGeneratorCategory_auditDeletedDateUtc DEFAULT (SYSUTCDATETIME ()),
        auditCreatedBy             NVARCHAR (128)                  NOT NULL CONSTRAINT DF_dbo_LookupGeneratorCategory_auditCreatedBy DEFAULT (ORIGINAL_LOGIN ()),
        auditCreatedDateUtc        DATETIME2                       NOT NULL CONSTRAINT DF_dbo_LookupGeneratorCategory_auditCreatedDateUtc DEFAULT (SYSUTCDATETIME ()),
        auditModifiedBy            NVARCHAR (128)                  NOT NULL CONSTRAINT DF_dbo_LookupGeneratorCategory_auditModifiedBy DEFAULT (ORIGINAL_LOGIN ()),
        auditModifiedDateUtc       DATETIME2                       NOT NULL CONSTRAINT DF_dbo_LookupGeneratorCategory_auditModifiedDateUtc DEFAULT (SYSUTCDATETIME ()),

        CONSTRAINT PK_dbo_LookupGeneratorCategory PRIMARY KEY CLUSTERED (LookupGeneratorCategoryId)
    )
    WITH (DATA_COMPRESSION = PAGE);
END;
GO

----------------------------------------------------------------------------------------------------
-- 2. Natural key.
--    A filtered unique index, not a unique constraint: a soft-deleted row keeps its key,
--    and an unfiltered constraint would block re-creation of that key forever -- the load
--    would fail on a handler EPA had corrected and resubmitted.
----------------------------------------------------------------------------------------------------
IF NOT EXISTS (SELECT 1
                 FROM sys.indexes
                WHERE name      = N'UX_dbo_LookupGeneratorCategory_Natural'
                  AND object_id = OBJECT_ID (N'dbo.LookupGeneratorCategory'))
BEGIN
    CREATE UNIQUE INDEX UX_dbo_LookupGeneratorCategory_Natural
        ON dbo.LookupGeneratorCategory (ActivityLocation, Code)
        WHERE IsDeleted = 0
        WITH (DATA_COMPRESSION = PAGE);
END;
GO

IF EXISTS (SELECT 1
             FROM sys.indexes AS i
             JOIN sys.partitions AS p
               ON p.object_id = i.object_id
              AND p.index_id  = i.index_id
            WHERE i.name      = N'UX_dbo_LookupGeneratorCategory_Natural'
              AND i.object_id = OBJECT_ID (N'dbo.LookupGeneratorCategory')
              AND p.data_compression_desc <> N'PAGE')
BEGIN
    ALTER INDEX UX_dbo_LookupGeneratorCategory_Natural
        ON dbo.LookupGeneratorCategory REBUILD WITH (DATA_COMPRESSION = PAGE);
END;
GO

/*
    Extended properties. Required on the table and on EVERY column.

    Through util.uspSetObjectDescription only. It adds or updates, so this script re-runs and
    an improved wording replaces the old one; a bare sp_addextendedproperty succeeds once and
    then fails on every subsequent run.

    Each column description ends with the RCRAInfo JSON path it mirrors. Flattening turned
    siteLocation.state.code into SiteLocationStateCode, and the way back is what a reader of
    this database needs. Where EPA's spec carries no description the placeholder says so
    rather than inventing one -- a wrong description in database metadata is worse than a
    missing one.
*/

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'LookupGeneratorCategory'
    , @Description = N'Mirror of the EPA RCRAInfo GeneratorCategory code list, served by /lookup/hd/generator-categories. Retired codes are SOFT-DELETED and must still resolve: a code EPA retires this year is still the correct code for a handler version submitted while it was current, so a historical read must NOT filter IsDeleted = 0 on this table. That is the one documented exception to this database''s blanket read rule. No handler table takes a foreign key to this one (see Phase1-Plan.md B2): the lists load independently, and a code that arrives on a handler before it appears in the mirrored list is a data-quality observation, not a failed load.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'LookupGeneratorCategory'
    , @ColumnName  = N'LookupGeneratorCategoryId'
    , @Description = N'Surrogate key. EPA''s natural key for this list is (ActivityLocation, Code), enforced by a filtered unique index.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'LookupGeneratorCategory'
    , @ColumnName  = N'ActivityLocation'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: GeneratorCategory.activityLocation]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'LookupGeneratorCategory'
    , @ColumnName  = N'Code'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: GeneratorCategory.code]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'LookupGeneratorCategory'
    , @ColumnName  = N'Description'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: GeneratorCategory.description]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'LookupGeneratorCategory'
    , @ColumnName  = N'Active'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: GeneratorCategory.active]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'LookupGeneratorCategory'
    , @ColumnName  = N'IsDeleted'
    , @Description = N'Soft-delete flag. 1 = deleted, 0 = active. This database performs no hard deletes; every read path filters IsDeleted = 0.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'LookupGeneratorCategory'
    , @ColumnName  = N'auditDeletedBy'
    , @Description = N'Login that soft-deleted the row. Populated by DEFAULT on insert, so it is only meaningful when IsDeleted = 1.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'LookupGeneratorCategory'
    , @ColumnName  = N'auditDeletedDateUtc'
    , @Description = N'UTC timestamp of the soft delete. Populated by DEFAULT on insert, so it is only meaningful when IsDeleted = 1; the deleting statement sets it explicitly.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'LookupGeneratorCategory'
    , @ColumnName  = N'auditCreatedBy'
    , @Description = N'Login that inserted the row. Under the application logins this identifies which application wrote it, not an end user.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'LookupGeneratorCategory'
    , @ColumnName  = N'auditCreatedDateUtc'
    , @Description = N'UTC timestamp of row insert. Set by DEFAULT; the loader omits this column from its INSERT column list so the default fires.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'LookupGeneratorCategory'
    , @ColumnName  = N'auditModifiedBy'
    , @Description = N'Login that last modified the row.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'LookupGeneratorCategory'
    , @ColumnName  = N'auditModifiedDateUtc'
    , @Description = N'UTC timestamp of last modification. The DEFAULT fires on INSERT only, so every UPDATE and MERGE must set this column explicitly or the audit trail will claim the row has never changed.';
GO

PRINT N'206: dbo.LookupGeneratorCategory created or altered, 12 column(s) described.';
GO
