/**********************************************************************************************************************
Script:       221_dbo.LookupStateDistrictCounty.sql
Author:       generated by build/generate_schema.py
========================================================================================================================
Description:

Mirrors EPA's StateDistrict.counties array -- the County entries belonging to each StateDistrict row -- one row per
element. County also has its own mirrored table; this one records the association, and carries the same columns rather
than a foreign key. Retired codes are SOFT-DELETED and must still resolve: a code EPA retires this year is still the
correct code for a handler version submitted while it was current, so a historical read must NOT filter IsDeleted = 0
on this table. That is the one documented exception to this database's blanket read rule. No handler table takes a
foreign key to this one (see Phase1-Plan.md B2): the lists load independently, and a code that arrives on a handler
before it appears in the mirrored list is a data-quality observation, not a failed load.

GENERATED FILE -- do not edit by hand. Regenerate with:

    python build/generate_schema.py

Generated from one lookup/hd response definition. Mirrored per G15. (Written without the glob character on purpose: a
T-SQL block comment nests, so a slash-star inside this header would swallow its own terminator.)

build/guardrails.py runs `generate_schema.py --check`, which fails if this file and the spec
have drifted apart, so editing it here is not merely discouraged -- it breaks the build.

========================================================================================================================
Notes:

RE-RUNNABLE. Every CREATE is guarded, descriptions go through util.uspSetObjectDescription
(which adds or updates), and nothing is dropped or truncated. A second run changes nothing.

Later changes are ADDITIVE: append a guarded ALTER TABLE ... ADD block rather than editing
the CREATE TABLE above, or the script stops converging on a database that already has the
table. In this file that means changing the generator, not the output.
**********************************************************************************************************************/

SET XACT_ABORT ON;
-- Not decoration: sqlcmd defaults QUOTED_IDENTIFIER OFF where every other client defaults it ON, the
-- setting is BAKED IN at CREATE time, and a module or session carrying it OFF cannot run DML against a
-- table with a filtered index (error 1934). Every unique constraint here is one. Set it so that a hand
-- run cannot get it wrong.
SET QUOTED_IDENTIFIER ON;
GO

----------------------------------------------------------------------------------------------------
-- 1. The table. Guarded, so a second run is a no-op.
----------------------------------------------------------------------------------------------------
IF OBJECT_ID (N'dbo.LookupStateDistrictCounty', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.LookupStateDistrictCounty
    (
        LookupStateDistrictCountyId  INT             IDENTITY (1, 1) NOT NULL,
        LookupStateDistrictId        INT                             NOT NULL,
        OrdinalPosition              INT                             NOT NULL,
        ActivityLocation             NVARCHAR (2)                        NULL,
        Code                         NVARCHAR (5)                        NULL,
        Description                  NVARCHAR (255)                      NULL,
        Active                       BIT                                 NULL,
        IsDeleted                    BIT                             NOT NULL CONSTRAINT DF_dbo_LookupStateDistrictCounty_IsDeleted DEFAULT (0),
        auditDeletedBy               NVARCHAR (128)                  NOT NULL CONSTRAINT DF_dbo_LookupStateDistrictCounty_auditDeletedBy DEFAULT (ORIGINAL_LOGIN ()),
        auditDeletedDateUtc          DATETIME2                       NOT NULL CONSTRAINT DF_dbo_LookupStateDistrictCounty_auditDeletedDateUtc DEFAULT (SYSUTCDATETIME ()),
        auditCreatedBy               NVARCHAR (128)                  NOT NULL CONSTRAINT DF_dbo_LookupStateDistrictCounty_auditCreatedBy DEFAULT (ORIGINAL_LOGIN ()),
        auditCreatedDateUtc          DATETIME2                       NOT NULL CONSTRAINT DF_dbo_LookupStateDistrictCounty_auditCreatedDateUtc DEFAULT (SYSUTCDATETIME ()),
        auditModifiedBy              NVARCHAR (128)                  NOT NULL CONSTRAINT DF_dbo_LookupStateDistrictCounty_auditModifiedBy DEFAULT (ORIGINAL_LOGIN ()),
        auditModifiedDateUtc         DATETIME2                       NOT NULL CONSTRAINT DF_dbo_LookupStateDistrictCounty_auditModifiedDateUtc DEFAULT (SYSUTCDATETIME ()),

        CONSTRAINT PK_dbo_LookupStateDistrictCounty PRIMARY KEY CLUSTERED (LookupStateDistrictCountyId)
    )
    WITH (DATA_COMPRESSION = PAGE);
END;
GO

----------------------------------------------------------------------------------------------------
-- 2. Natural key.
--    A filtered unique index, not a unique constraint: a soft-deleted row keeps its key,
--    and an unfiltered constraint would block re-creation of that key forever -- the load
--    would fail on a handler EPA had corrected and resubmitted.
----------------------------------------------------------------------------------------------------
IF NOT EXISTS (SELECT 1
                 FROM sys.indexes
                WHERE name      = N'UX_dbo_LookupStateDistrictCounty_Natural'
                  AND object_id = OBJECT_ID (N'dbo.LookupStateDistrictCounty'))
BEGIN
    CREATE UNIQUE INDEX UX_dbo_LookupStateDistrictCounty_Natural
        ON dbo.LookupStateDistrictCounty (LookupStateDistrictId, OrdinalPosition)
        WHERE IsDeleted = 0
        WITH (DATA_COMPRESSION = PAGE);
END;
GO

IF EXISTS (SELECT 1
             FROM sys.indexes AS i
             JOIN sys.partitions AS p
               ON p.object_id = i.object_id
              AND p.index_id  = i.index_id
            WHERE i.name      = N'UX_dbo_LookupStateDistrictCounty_Natural'
              AND i.object_id = OBJECT_ID (N'dbo.LookupStateDistrictCounty')
              AND p.data_compression_desc <> N'PAGE')
BEGIN
    ALTER INDEX UX_dbo_LookupStateDistrictCounty_Natural
        ON dbo.LookupStateDistrictCounty REBUILD WITH (DATA_COMPRESSION = PAGE);
END;
GO

----------------------------------------------------------------------------------------------------
-- 3. The foreign key column.
--    Deliberately NOT redundant with UX_dbo_LookupStateDistrictCounty_Natural above. That index is filtered to
--    IsDeleted = 0, so it cannot serve a lookup that has to see soft-deleted rows -- and
--    for this loader that is a normal path, not an exceptional one. Nothing is ever hard-
--    deleted, so re-loading a handler means finding the existing child rows, including any
--    previously soft-deleted, and reviving them. Without this index that seek is a scan of
--    every child row in the table, for every handler in the batch.
----------------------------------------------------------------------------------------------------
IF NOT EXISTS (SELECT 1
                 FROM sys.indexes
                WHERE name      = N'IX_dbo_LookupStateDistrictCounty_LookupStateDistrictId'
                  AND object_id = OBJECT_ID (N'dbo.LookupStateDistrictCounty'))
BEGIN
    CREATE INDEX IX_dbo_LookupStateDistrictCounty_LookupStateDistrictId
        ON dbo.LookupStateDistrictCounty (LookupStateDistrictId)
        WITH (DATA_COMPRESSION = PAGE);
END;
GO

IF EXISTS (SELECT 1
             FROM sys.indexes AS i
             JOIN sys.partitions AS p
               ON p.object_id = i.object_id
              AND p.index_id  = i.index_id
            WHERE i.name      = N'IX_dbo_LookupStateDistrictCounty_LookupStateDistrictId'
              AND i.object_id = OBJECT_ID (N'dbo.LookupStateDistrictCounty')
              AND p.data_compression_desc <> N'PAGE')
BEGIN
    ALTER INDEX IX_dbo_LookupStateDistrictCounty_LookupStateDistrictId
        ON dbo.LookupStateDistrictCounty REBUILD WITH (DATA_COMPRESSION = PAGE);
END;
GO

----------------------------------------------------------------------------------------------------
-- Foreign key to the parent version. NO ACTION on delete, not CASCADE: this database
--    performs no hard deletes, so a cascade could never fire and declaring one would
--    advertise a behaviour that does not exist.
----------------------------------------------------------------------------------------------------
IF NOT EXISTS (SELECT 1
                 FROM sys.foreign_keys
                WHERE name = N'FK_dbo_LookupStateDistrictCounty_LookupStateDistrict')
BEGIN
    ALTER TABLE dbo.LookupStateDistrictCounty
        ADD CONSTRAINT FK_dbo_LookupStateDistrictCounty_LookupStateDistrict FOREIGN KEY (LookupStateDistrictId)
            REFERENCES dbo.LookupStateDistrict (LookupStateDistrictId);
END;
GO

/*
    Extended properties. Required on the table and on EVERY column.

    Through util.uspSetObjectDescription only. It adds or updates, so this script re-runs and
    an improved wording replaces the old one; a bare sp_addextendedproperty succeeds once and
    then fails on every subsequent run.

    Each column description ends with the RCRAInfo JSON path it mirrors. Flattening turned
    siteLocation.state.code into SiteLocationStateCode, and the way back is what a reader of
    this database needs. Where EPA's spec carries no description the placeholder says so
    rather than inventing one -- a wrong description in database metadata is worse than a
    missing one.
*/

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'LookupStateDistrictCounty'
    , @Description = N'Mirrors EPA''s StateDistrict.counties array -- the County entries belonging to each StateDistrict row -- one row per element. County also has its own mirrored table; this one records the association, and carries the same columns rather than a foreign key. Retired codes are SOFT-DELETED and must still resolve: a code EPA retires this year is still the correct code for a handler version submitted while it was current, so a historical read must NOT filter IsDeleted = 0 on this table. That is the one documented exception to this database''s blanket read rule. No handler table takes a foreign key to this one (see Phase1-Plan.md B2): the lists load independently, and a code that arrives on a handler before it appears in the mirrored list is a data-quality observation, not a failed load.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'LookupStateDistrictCounty'
    , @ColumnName  = N'LookupStateDistrictCountyId'
    , @Description = N'Surrogate key for one element of EPA''s StateDistrict.counties array.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'LookupStateDistrictCounty'
    , @ColumnName  = N'LookupStateDistrictId'
    , @Description = N'The dbo.LookupStateDistrict row this element belongs to.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'LookupStateDistrictCounty'
    , @ColumnName  = N'OrdinalPosition'
    , @Description = N'Zero-based position within EPA''s StateDistrict.counties array. EPA supplies no key for these elements, so the position is both the fidelity of the mirror and the only natural key.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'LookupStateDistrictCounty'
    , @ColumnName  = N'ActivityLocation'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: County.activityLocation]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'LookupStateDistrictCounty'
    , @ColumnName  = N'Code'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: County.code]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'LookupStateDistrictCounty'
    , @ColumnName  = N'Description'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: County.description]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'LookupStateDistrictCounty'
    , @ColumnName  = N'Active'
    , @Description = N'TODO: awaiting EPA data dictionary. [RCRAInfo: County.active]';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'LookupStateDistrictCounty'
    , @ColumnName  = N'IsDeleted'
    , @Description = N'Soft-delete flag. 1 = deleted, 0 = active. This database performs no hard deletes; every read path filters IsDeleted = 0.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'LookupStateDistrictCounty'
    , @ColumnName  = N'auditDeletedBy'
    , @Description = N'Login that soft-deleted the row. Populated by DEFAULT on insert, so it is only meaningful when IsDeleted = 1.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'LookupStateDistrictCounty'
    , @ColumnName  = N'auditDeletedDateUtc'
    , @Description = N'UTC timestamp of the soft delete. Populated by DEFAULT on insert, so it is only meaningful when IsDeleted = 1; the deleting statement sets it explicitly.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'LookupStateDistrictCounty'
    , @ColumnName  = N'auditCreatedBy'
    , @Description = N'Login that inserted the row. Under the application logins this identifies which application wrote it, not an end user.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'LookupStateDistrictCounty'
    , @ColumnName  = N'auditCreatedDateUtc'
    , @Description = N'UTC timestamp of row insert. Set by DEFAULT; the loader omits this column from its INSERT column list so the default fires.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'LookupStateDistrictCounty'
    , @ColumnName  = N'auditModifiedBy'
    , @Description = N'Login that last modified the row.';
GO

EXEC util.uspSetObjectDescription
      @SchemaName  = N'dbo'
    , @ObjectType  = N'TABLE'
    , @ObjectName  = N'LookupStateDistrictCounty'
    , @ColumnName  = N'auditModifiedDateUtc'
    , @Description = N'UTC timestamp of last modification. The DEFAULT fires on INSERT only, so every UPDATE and MERGE must set this column explicitly or the audit trail will claim the row has never changed.';
GO

PRINT N'221: dbo.LookupStateDistrictCounty created or altered, 14 column(s) described.';
GO
