/**********************************************************************************************************************
Script:       391_dbo.LookupWasteCode_Widths.sql
Author:       rsincero
CreateDate:   2026-09-06
========================================================================================================================
Description:

Widens dbo.LookupWasteCode.Description from NVARCHAR (255) to NVARCHAR (4000) and CodeType from NVARCHAR (10) to
NVARCHAR (50) on a database that already holds the table.

WHY THIS IS A SEPARATE SCRIPT. 223_dbo.LookupWasteCode.sql is generated by build/generate_schema.py and its CREATE
TABLE is guarded, so on an established database it is a no-op and could never widen anything -- the generator now
emits the new widths, which serves a fresh deployment and nothing else. Editing the generated file to carry an ALTER
would also break build/guardrails.py, which runs generate_schema.py --check. So the convergence lives here, beside it,
and the two agree: after both have run, a new database and an old one have the same column widths.

WHY THE NUMBER IS 391 AND NOT 224. build/generate_schema.py claims whole leading digits: OWNED_PREFIXES is 1xx, 2xx
and 4xx, and --check reports any script in those ranges that the generator does not produce as stale. 3xx is the
hand-authored DDL range, and it still deploys after every table and before every procedure -- which is the order an
ALTER COLUMN needs. 390_dbo.HandlerSource_GridIndex.sql sits here for exactly the same reason, so the two
hand-authored additions to generated tables are adjacent.

WHY THE WIDTHS CHANGED. Load run 2621 -- the first run to exercise the lookup stage against EPA -- was refused by
script 523's width check: "Element 3 of 15 in the WasteCode list carries a value wider than the column that stores it".
EPA declares NO maxLength for either property in its response definition, so 255 and 10 were never EPA's bounds, only
ours: 255 came from an analogy with episodic.projects[].otherDescription and 10 from the incorrect inference that a
code's classifier cannot be wider than the widest code. Neither survived contact with the data. The published bound
this list DOES carry -- code, maxLength 6 -- is deliberately left alone, because a code that does not fit is not a
long code, it is a different code, and script 523 is right to refuse it.

4000 is the true ceiling for Description whatever this column says: script 523 shreds the value with JSON_VALUE, which
returns NULL in lax mode for anything longer than 4000 characters rather than clipping it.

========================================================================================================================
Notes:

RE-RUNNABLE. Each ALTER is guarded on the column's current width in sys.columns, so a second run changes nothing and
reports nothing.

WIDENING ONLY, NEVER NARROWING. The guards test for a column NARROWER than the target, not merely different. An
ALTER COLUMN that narrows an NVARCHAR truncates the values in it, and truncation is a hard delete of real data --
this database performs none anywhere. So a column already at or above the target is left exactly as it is.

Nothing is dropped, and neither column participates in an index: UX_dbo_LookupWasteCode_Natural covers
(ActivityLocation, Code). Widening is therefore a metadata-only change for Description and CodeType.
**********************************************************************************************************************/

SET XACT_ABORT ON;
-- Not decoration: sqlcmd defaults QUOTED_IDENTIFIER OFF where every other client defaults it ON, and a session
-- carrying it OFF cannot run DML against a table with a filtered index (error 1934). This table has one.
SET QUOTED_IDENTIFIER ON;
GO

----------------------------------------------------------------------------------------------------
-- 1. Description: NVARCHAR (255) -> NVARCHAR (4000).
--    max_length is in BYTES for NVARCHAR, so 4000 characters is 8000.
----------------------------------------------------------------------------------------------------
IF OBJECT_ID (N'dbo.LookupWasteCode', N'U') IS NOT NULL
   AND EXISTS (SELECT 1
                 FROM sys.columns
                WHERE object_id  = OBJECT_ID (N'dbo.LookupWasteCode')
                  AND name       = N'Description'
                  AND max_length < 8000
                  AND max_length > 0)   -- > 0 excludes NVARCHAR (MAX), which reports -1 and is already wider
BEGIN
    ALTER TABLE dbo.LookupWasteCode
        ALTER COLUMN Description NVARCHAR (4000) NULL;

    PRINT N'391: dbo.LookupWasteCode.Description widened to NVARCHAR (4000).';
END;
GO

----------------------------------------------------------------------------------------------------
-- 2. CodeType: NVARCHAR (10) -> NVARCHAR (50).
----------------------------------------------------------------------------------------------------
IF OBJECT_ID (N'dbo.LookupWasteCode', N'U') IS NOT NULL
   AND EXISTS (SELECT 1
                 FROM sys.columns
                WHERE object_id  = OBJECT_ID (N'dbo.LookupWasteCode')
                  AND name       = N'CodeType'
                  AND max_length < 100
                  AND max_length > 0)
BEGIN
    ALTER TABLE dbo.LookupWasteCode
        ALTER COLUMN CodeType NVARCHAR (50) NULL;

    PRINT N'391: dbo.LookupWasteCode.CodeType widened to NVARCHAR (50).';
END;
GO

----------------------------------------------------------------------------------------------------
-- 3. Report the state either way, so a re-run says something true rather than nothing at all.
----------------------------------------------------------------------------------------------------
IF OBJECT_ID (N'dbo.LookupWasteCode', N'U') IS NOT NULL
BEGIN
    DECLARE @DescriptionChars INT
          , @CodeTypeChars    INT;

    SELECT @DescriptionChars = MAX (CASE WHEN name = N'Description' THEN max_length / 2 END)
         , @CodeTypeChars    = MAX (CASE WHEN name = N'CodeType'    THEN max_length / 2 END)
      FROM sys.columns
     WHERE object_id = OBJECT_ID (N'dbo.LookupWasteCode');

    PRINT CONCAT (N'391: dbo.LookupWasteCode.Description is NVARCHAR (', @DescriptionChars
                , N'), CodeType is NVARCHAR (', @CodeTypeChars
                , N'). Code is left at its EPA-published maxLength of 6 on purpose.');
END;
GO
