using System.Runtime.Versioning;
using System.Security.Cryptography;
using RCRAInfo.Core.Credentials;

namespace RCRAInfo.Core.Tests;

/// <summary>
/// The AR4 protection mechanism itself, against real DPAPI.
/// </summary>
/// <remarks>
/// No substitute here. The three failures this class cares about — a value that was never sealed, a value
/// edited after it was sealed, and the other application's value — are all properties of DPAPI rather
/// than of the calling code, and a fake protector would report whatever it was told to report.
/// </remarks>
[SupportedOSPlatform("windows")]
public sealed class DpapiSecretProtectorTests
{
    private static readonly DpapiSecretProtector Loader = new(ApplicationIdentity.Loader);

    [Theory]
    [InlineData("sql-password-QQ7MARKERf3")]
    [InlineData("a")]
    [InlineData("Pa$$w0rd with spaces, \"quotes\", \\backslashes\\ and a } brace")]
    [InlineData("pá$$wörd-Ünïcøde-þЖ中文")]
    public void WhatIsSealedComesBackExactly(string plaintext)
    {
        // Unicode and punctuation are here because the password is generated by a password manager and
        // then pasted into a JSON file: the two places it could be mangled are the UTF-8 round trip and
        // the JSON escaping, and both are on this path.
        Assert.Equal(plaintext, Loader.Unprotect(Loader.Protect(plaintext)));
    }

    [Fact]
    public void ALongValueRoundTrips()
    {
        // EPA's API Key is an opaque token of unpublished length, and G1 has not told us what it is yet.
        string plaintext = new string('k', 4096);

        Assert.Equal(plaintext, Loader.Unprotect(Loader.Protect(plaintext)));
    }

    [Fact]
    public void SealingTheSameValueTwiceProducesDifferentCiphertext()
    {
        // Not a nicety. The loader's and the monitor's files sit on the same machine, readable by an
        // administrator; if identical passwords sealed to identical text, comparing the two files would
        // reveal that the two SQL logins share a password without decrypting either one.
        Assert.NotEqual(Loader.Protect(Secrets.SqlPassword), Loader.Protect(Secrets.SqlPassword));
    }

    [Fact]
    public void AValueThatWasNeverSealedIsRefusedWithoutBeingQuoted()
    {
        // G5 row 3, in its most likely form: someone set Encrypted to true by hand.
        CryptographicException error =
            Assert.Throws<CryptographicException>(() => Loader.Unprotect(Secrets.SqlPassword));

        Assert.DoesNotContain(Secrets.SqlPassword, error.Message, StringComparison.Ordinal);

        // The length is the one detail that tells an operator which mistake this is -- a 24-character
        // value was never ciphertext; a 300-character one was truncated.
        Assert.Contains(
            Secrets.SqlPassword.Length.ToString(System.Globalization.CultureInfo.InvariantCulture),
            error.Message,
            StringComparison.Ordinal);
    }

    [Fact]
    public void ValidBase64ThatIsNotADpapiBlobIsRefused()
    {
        // The other half of "not sealed by this application": text that passes the Base64 decode and
        // then fails DPAPI's own integrity check. Both must be CryptographicException, because
        // ISecretProtector contracts a single exception type for every cause -- the caller's response is
        // the same one either way.
        Assert.Throws<CryptographicException>(
            () => Loader.Unprotect(Convert.ToBase64String([1, 2, 3, 4, 5, 6, 7, 8])));
    }

    [Fact]
    public void CiphertextAlteredAfterItWasSealedIsRefused()
    {
        string tampered = Tamper.OneCharacterOf(Loader.Protect(Secrets.SqlPassword));

        Assert.Throws<CryptographicException>(() => Loader.Unprotect(tampered));
    }

    [Fact]
    public void TheProviderGuidInTheBlobHeaderIsNotAuthenticatedAndThatIsRecordedHere()
    {
        // Not an aspiration -- a measurement, and the reason Tamper.OneCharacterOf alters the tail. Bytes
        // 4 through 19 of a DPAPI blob are the provider GUID, and CryptUnprotectData ignores them: alter
        // one and the value still decrypts. The first version of the tamper tests altered Base64
        // character 10, which lands on byte 6, and they failed for that reason.
        //
        // It matters beyond the tests. "The ciphertext is authenticated" is true of the payload and NOT
        // of the whole stored string, so nothing in this solution may treat a byte-for-byte comparison of
        // two sealed values as a comparison of what they hold.
        byte[] blob = Convert.FromBase64String(Loader.Protect(Secrets.SqlPassword));
        blob[6] ^= 0xFF;

        Assert.Equal(Secrets.SqlPassword, Loader.Unprotect(Convert.ToBase64String(blob)));

        // The neighbouring byte, one past the provider GUID, is authenticated -- the positive control
        // that keeps this test from passing on a build where DPAPI checked nothing at all.
        blob = Convert.FromBase64String(Loader.Protect(Secrets.SqlPassword));
        blob[20] ^= 0xFF;

        Assert.Throws<CryptographicException>(() => Loader.Unprotect(Convert.ToBase64String(blob)));
    }

    [Fact]
    public void NeitherApplicationCanOpenTheOthersValue()
    {
        // The entropy claim, measured in both directions. It is hygiene rather than a boundary -- both
        // blobs are LocalMachine and an administrator can read either -- but it does stop the realistic
        // accident, which is an operator copying one application's secrets.json into the other's
        // directory and getting a confusing SQL login failure instead of a clear refusal.
        DpapiSecretProtector monitor = new(ApplicationIdentity.Monitor);

        Assert.Throws<CryptographicException>(() => monitor.Unprotect(Loader.Protect(Secrets.SqlPassword)));
        Assert.Throws<CryptographicException>(() => Loader.Unprotect(monitor.Protect(Secrets.SqlPassword)));
    }

    [Fact]
    public void AnUnknownApplicationIsRefusedRatherThanGivenDefaultEntropy()
    {
        // An enum parameter accepts any int, and the switch's default arm is the difference between a
        // loud failure here and a file that seals with all-zero entropy, round-trips in the process that
        // wrote it, and fails only on the next machine.
        ArgumentOutOfRangeException error = Assert.Throws<ArgumentOutOfRangeException>(
            () => new DpapiSecretProtector((ApplicationIdentity)99));

        Assert.Equal("application", error.ParamName);
    }

    [Fact]
    public void NeitherOperationAcceptsNull()
    {
        Assert.Throws<ArgumentNullException>(() => Loader.Protect(null!));
        Assert.Throws<ArgumentNullException>(() => Loader.Unprotect(null!));
    }
}
